local Changelogs = "View the change logs at https://docs.rifton.top/changelogs."

local Success, Response = pcall(function()
    return request({
        Url = "https://docs.rifton.top/changelogs/rss.xml",
        Method = "GET"
    })
end)

if Success and Response.Success then
    local Body = Response.Body
    local LatestItem = Body:match("<item>(.-)</item>")
    local Description, Title
    if LatestItem then
        Description = LatestItem:match("<description><!%[CDATA%[(.-)%]%]></description>") 
                      or LatestItem:match("<description>(.-)</description>")
                      or LatestItem:match("<content:encoded><!%[CDATA%[(.-)%]%]></content:encoded>")
                      or LatestItem:match("<content:encoded>(.-)</content:encoded>")
        Title = LatestItem:match("<title><!%[CDATA%[(.-)%]%]></title>") or LatestItem:match("<title>(.-)</title>")
    end

    if Description and Title then
        Description = Description
            :gsub("&lt;", "<"):gsub("&gt;", ">"):gsub("&amp;", "&")
            :gsub("&quot;", '"'):gsub("&#39;", "'")
            :gsub("<ul>", ""):gsub("</ul>", "")
            :gsub("<ol>", ""):gsub("</ol>", "")
            :gsub("<li>", "• "):gsub("</li>", "\n")
            :gsub("<br ?/?>", "\n")
            :gsub("<p>", ""):gsub("</p>", "\n")
            :gsub("<strong>", "<b>"):gsub("</strong>", "</b>")
            :gsub("<em>", "<i>"):gsub("</em>", "</i>")
            :gsub("<u>", "<u>"):gsub("</u>", "</u>")
            :gsub("<(?!/?(b|i|u|font)).->", "")
            :gsub("\n+", "\n")
            :gsub("\n+$", "")
    
        Changelogs = string.format('<font size="15"><b><u>%s</u></b></font>%s', Title, Description)
    end
end

return {
    VERSION = "1.25.23.9",
    CHANNEL = "Beta",
    ADVERTISEMENT_ENABLED = false,
    CHANGELOGS = Changelogs .. "\n\nThis update log may not be up to date!",
    GAMES_SUPPORTED =  "<font color=\"#00ff00\">◉</font> → Maintained & Updated\n" ..
            "<font color=\"#ffff00\">◉</font> → Experimental / Has Issues\n" ..
            "<font color=\"#ff0000\">◉</font> → Offline / Broken\n\n" ..
            "<font color=\"#00ff00\">◉</font> <b>Grow a Garden</b>\n" ..
            "<font color=\"#00ff00\">◉</font> <b>99 Nights in the Forest</b>\n" ..
            "<font color=\"#00ff00\">◉</font> <b>Steal a Brainrot</b>\n" ..
            "<font color=\"#00ff00\">◉</font> <b>Plants Vs Brainrots</b>\n" ..
            "<font color=\"#00ff00\">◉</font> <b>Fisch</b>\n" ..
            "<font color=\"#00ff00\">◉</font> <b>Forsaken</b>\n" ..
            "<font color=\"#00ff00\">◉</font> <b>Dead Rails</b>",
    SCRIPT_NAMES = {
        "BetterBypasser (Chat Bypass)",
        "Rizzler"
    },
    SCRIPT_LINKS = {
        ["Rizzler"] = [[-- Discord Server: https://vaultcord.win/synergy
-- Join our server to get consistent updates about our products and services

loadstring(game:HttpGet("https://raw.githubusercontent.com/Synergy-Networks/OpenSource/main/rizzler.lua"))()]],
        ["BetterBypasser (Chat Bypass)"] = [[loadstring(game:HttpGet("https://github.com/Synergy-Networks/products/raw/main/BetterBypasser/loader.lua"))()]]
    },
    ADVERTISEMENTS = {
        'We added a <font color="#DC551E"><b>INF TIER 3 CARD CONVERTER</b></font> for Plants vs Brainrots. Come check it out!'
    },
    KEY_SYS_INFO = 
        "<font color='%AccentColor%'>❖ Tired of the key system?</font>\n" ..
        "<font color='%AccentColor%'>·</font> You can buy a key by visiting https://rifton.top/resellers and purchasing it using various payment methods. \n\n" ..

        "<font color='%AccentColor%'>❖ How many checkpoints are there?</font>\n" ..
        "<font color='%AccentColor%'>·</font> There are two checkpoints which give you 24-hour access to Rift under a key.\n\n" ..

        "<font color='%AccentColor%'>❖ Why won't the page load?</font>\n" ..
        "<font color='%AccentColor%'>·</font> Try using a browser like Google Chrome.\n" ..
        "<font color='%AccentColor%'>·</font> Disable any firewalls, VPNs/proxies, or antivirus software that might block the page.\n\n" ..

        "<font color='%AccentColor%'>❖ Why is my key invalid?</font>\n" ..
        "<font color='%AccentColor%'>·</font> Make sure there are no extra spaces in the key.\n" ..
        "<font color='%AccentColor%'>·</font> Keys generated by others are not usable by you."
}
