return {
    WorldEvents = {
        "Luminescent Cavern",
        "Crimson Cavern",
        "Carrot Garden",
        "AFK Pool - Trading Plaza",
        "Gilded Arch",
        "Castaway Cliffs",
        "Magician Narwhal - Sea 2",
        "Magician Narwhal - Sea 1",
        "Beluga - Sea 2",
        "Beluga - Sea 1",
        "Narwhal - Sea 2",
        "Narwhal - Sea 1",
        "Apex Leviathan",
        "Mosslurker",
        "Bloop Fish",
        "Colossal Ethereal Dragon",
        "Colossal Blue Dragon",
        "Colossal Ancient Dragon",
        "Animal Pool",
        "Animal Pool - Second Sea",
        "Octophant Pool Without Elephant",
        "Octophant Pool With Elephant",
        "Sea Leviathan Pool",
        "Smurf Pool",
        "Smurf Storm Pool",
        "Sunny O'Coin",
        "Rowdy McCharm",
        "Plumrick O'Luck",
        "O'Mango Goldgrin",
        "Clover McRich",
        "Blarney McBreeze",
        "Ashfall Pool",
        "Cults Curse Pool",
        "Ancient Orcas Pool",
        "Orcas Pool",
        "Whales Pool",
        "Notes Island Pool",
        "Atlantean Storm",
        "The Depths - Serpent",
        "The Depths",
        "Crystal Cove",
        "Fischfest",
        "Ocean Greedy",
        "Ocean",
        "Deep Ocean",
        "Atlantis Ocean",
        "Grand Reef",
        "Forsaken Shores",
        "Forsaken Shores Ocean",
        "Forsaken Shores Pond",
        "Moosewood Ocean",
        "Moosewood Ocean Mythical",
        "Moosewood Docks",
        "Moosewood Pond",
        "Lava",
        "Roslit Pond",
        "Roslit Pond Seaweed",
        "Roslit Bay",
        "Roslit Bay Ocean",
        "Roslit Bay Clam",
        "Desolate Deep",
        "Brine Pool",
        "Brine Pool Water",
        "Ancient Isle Ocean",
        "Ancient Isle Pond",
        "Ancient Isle Waterfall",
        "Ancient Archives",
        "Terrapin Ocean",
        "Terrapin Olm",
        "Mushgrove Water",
        "Vertigo",
        "Snowcap Pond",
        "Snowcap Ocean",
        "Snowburrow",
        "Sunstone",
        "Sunstone Hidden",
        "Keepers Altar",
        "Harvesters Spike",
        "The Arch",
        "Scallop Ocean",
        "Debug",
        "Relics",
        "ExaltedRelics",
        "CosmicRelic",
        "EmojiFish",
        "Lovestorm Eel",
        "Lovestorm Eel Supercharged",
        "Megalodon Default",
        "Megalodon Ancient",
        "Great White Shark",
        "Great Hammerhead Shark",
        "Whale Shark",
        "Isonade",
        "FischFright24",
        "Fischgiving",
        "Fischmas24",
        "Overgrowth Caves",
        "Frigid Cavern",
        "Cryogenic Canal",
        "Glacial Grotto",
        "The Summit Ocean",
        "Forsaken Algae Pool",
        "Ancient Algae Pool",
        "Mushgrove Algae Pool",
        "Snowcap Algae Pool",
        "Golden Tide",
        "Zeus Pool",
        "Poseidon Pool",
        "Sunken's Depth",
        "Ethereal Abyss",
        "Kraken Pool",
        "The Kraken Pool",
        "Ancient Kraken Pool",
        "Volcanic Vents",
        "Challengers Deep",
        "Abyssal Zenith",
        "Calm Zone",
        "Forsaken Veil",
        "Forsaken Veil - Scylla",
        "Waveborne",
        "Pine Shoal",
        "Lushgrove",
        "Emberreach",
        "Emberreach Ponds",
        "Emberreach Lava",
        "Isle of New Beginnings",
        "Cursed Isle",
        "Open Ocean",
        "Azure Lagoon",
        "Blue Moon - First Sea",
        "Blue Moon - Second Sea",
        "Jurassic Island Pool",
        "Jurassic Island Ocean Pool",
        "Mosasaurus Damage Pool",
        "LEGO",
        "LEGO - Studolodon",
        "Whale Interior",
        "Treasure Island"
    },
    Rarities = {
        ["Trash"] = Color3.fromRGB(145, 145, 145),
        ["Common"] = Color3.fromRGB(142, 187, 191),
        ["Uncommon"] = Color3.fromRGB(161, 255, 169),
        ["Unusual"] = Color3.fromRGB(192, 135, 198),
        ["Rare"] = Color3.fromRGB(119, 108, 181),
        ["Legendary"] = Color3.fromRGB(240, 181, 109),
        ["Mythical"] = Color3.fromRGB(255, 62, 120),
        ["Exotic"] = Color3.fromRGB(255, 255, 255),
        ["Secret"] = Color3.fromRGB(255, 255, 255),
        ["Limited"] = Color3.fromRGB(255, 130, 57),
        ["Extinct"] = Color3.fromRGB(54, 73, 159),
        ["Relic"] = Color3.fromRGB(120, 255, 183)
    },
    SecondSeaCrates = {
        "Tropical Bait Crate"
    },
    RodSpots = {
        ["Volcanic Rod"] = CFrame.new(-3178.2446289062, -2034.2508544922, 4021.5788574219, 1, 0, 0, 0, 1, 0, 0, 0, 1),
        ["Rod Of The Zenith"] = CFrame.new(-13625.116210938, -11032.931640625, 357.60198974609, 0.76606124639511, 0, -0.64276760816574, 0, 1, 0, 0.64276760816574, 0, 0.76606124639511),
        ["Challenger's Rod"] = CFrame.new(738, -3355, -1529, 1, 0, 0, 0, 1, 0, 0, 0, 1),
        ["Leviathan's Fang Rod"] = CFrame.new(-2297.6765136719, -11183.801757812, 7138.990234375, 1, 0, 0, 0, 1, 0, 0, 0, 1),
        ["Ethereal Prism Rod"] = CFrame.new(-4359.8618164062, -11170.938476562, 3719.0483398438, -0.17294538021088, -0.015099253505468, -0.98481571674347, -0.087165221571922, 0.99619388580322, 3.3542513847351e-05, 0.98106682300568, 0.085847474634647, -0.17360317707062)
    },
    Codes = {
        "THEKRAKEN",
        "CARBON",
        "SORRYGUYS",
        "ATLANTEANSTORM",
        "GOLDENTIDE",
        "NewYear",
        "FISCHMASDAY",
        "NorthernExpedition",
        "MERRYFISCHMAS",
        "RFG",
        "SorryReward"
    },
}
