local v1 = {
    ["Zeus Rod"] = {
        ["Passive"] = "ZeusRod",
        ["Price"] = 1700000,
        ["Description"] = "\t\t\tForged in the heart of Mount Olympus, this divine rod crackles with Zeus\'s lightning.\n\t\t\tIts celestial power grants unprecedented casting speed and the ability to command storms,\n\t\t\tmaking it a formidable tool for the most ambitious anglers.\n\t\t",
        ["Luck"] = 70,
        ["LureSpeed"] = 30,
        ["Strength"] = (1 / 0),
        ["LineDistance"] = 70,
        ["Resilience"] = 20,
        ["Control"] = 0.15,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(245, 205, 48),
        ["BobberBottom"] = Color3.fromRGB(20, 20, 20)
    },
    ["Poseidon Rod"] = {
        ["Passive"] = "PoseidonRod",
        ["Price"] = 1555555,
        ["Description"] = "\t\t\tBlessed by the God of the Seas himself, this trident-inspired rod commands the ocean\'s bounty.\n\t\t\tIts golden gleam attracts the most valuable aquatic treasures, while its divine essence ensures catches of legendary proportions.\n\t\t",
        ["Luck"] = 165,
        ["LureSpeed"] = 50,
        ["Strength"] = 100000,
        ["LineDistance"] = 65,
        ["Resilience"] = 40,
        ["Control"] = 0.2,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(255, 170, 0),
        ["BobberBottom"] = Color3.fromRGB(34, 191, 134)
    },
    ["Kraken Rod"] = {
        ["Passive"] = "KrakenRod",
        ["Price"] = 1333333,
        ["Description"] = "\t\t\tCrafted from the tentacle of an ancient Kraken, this mysterious rod pulses with dark energy.\n\t\t\tIts otherworldly power guarantees mythical catches,\n\t\t\twhile its curse brings forth mutated specimens and doubles your haul through supernatural means.\n\t\t",
        ["Luck"] = 185,
        ["LureSpeed"] = 40,
        ["Strength"] = 115000,
        ["LineDistance"] = 60,
        ["Resilience"] = 15,
        ["Control"] = 0.2,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(170, 0, 0),
        ["BobberBottom"] = Color3.fromRGB(85, 0, 0)
    },
    ["Tempest Rod"] = {
        ["Price"] = 1850000,
        ["Description"] = "\t\t\tBorn from the essence of a perpetual storm, this rod moves faster than the eye can follow.\n\t\t\tIts wind-blessed line cuts through water like lightning, allowing for rapid-fire casting and retrieval that leaves other anglers in awe.\n\t\t",
        ["Luck"] = 120,
        ["LureSpeed"] = 10,
        ["Strength"] = 80000,
        ["LineDistance"] = 20,
        ["Resilience"] = 40,
        ["Control"] = 0.15,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(220, 220, 220),
        ["BobberBottom"] = Color3.fromRGB(85, 255, 255)
    },
    ["Abyssal Specter Rod"] = {
        ["Price"] = 1000000,
        ["Description"] = "\t\t\tForged in the darkest depths of the ocean\'s trenches, this spectral rod radiates an otherworldly strength.\n\t\t\tIts phantom line reaches impossible depths, while its ghostly power grants the ability to haul in catches that would snap lesser rods.\n\t\t",
        ["Luck"] = 90,
        ["LureSpeed"] = 40,
        ["Strength"] = (1 / 0),
        ["LineDistance"] = 80,
        ["Resilience"] = 70,
        ["Control"] = 0.3,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(47, 245, 172),
        ["BobberBottom"] = Color3.fromRGB(26, 26, 26)
    },
    ["Champions Rod"] = {
        ["Price"] = 80000,
        ["Description"] = "\t\t\tWielded by legendary tournament winners, this balanced rod embodies competitive excellence.\n\t\t\tIts versatile design combines tournament-tested speed with professional-grade strength, making it the perfect choice for aspiring champions.\n\t\t",
        ["Luck"] = 65,
        ["LureSpeed"] = 55,
        ["Strength"] = 200000,
        ["LineDistance"] = 20,
        ["Resilience"] = 30,
        ["Control"] = 0.25,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(245, 205, 48),
        ["BobberBottom"] = Color3.fromRGB(255, 170, 0)
    },
    ["Depthseeker Rod"] = {
        ["Price"] = 40000,
        ["Description"] = "\t\t\tEngineered with deep-sea technology, this resilient rod thrives in challenging conditions.\n\t\t\tIts reinforced construction and adaptive strength make it ideal for anglers\n\t\t\tready to venture beyond the shallows and face tougher aquatic adversaries.\n\t\t",
        ["Luck"] = 70,
        ["LureSpeed"] = 45,
        ["Strength"] = 50000,
        ["LineDistance"] = 50,
        ["Resilience"] = 25,
        ["Control"] = 0.17,
        ["Color"] = Color3.fromRGB(245, 205, 48),
        ["BobberTop"] = Color3.fromRGB(66, 255, 239),
        ["BobberBottom"] = Color3.fromRGB(27, 27, 27)
    },
    ["Flimsy Rod"] = {
        ["Price"] = 0,
        ["Description"] = "Quite the weak and unreliable rod. But, it can get the job done!",
        ["Luck"] = 0,
        ["LureSpeed"] = 100,
        ["Strength"] = 10.4,
        ["LineDistance"] = 19,
        ["Resilience"] = 0,
        ["Control"] = 0,
        ["Color"] = Color3.fromRGB(154, 170, 190),
        ["BobberTop"] = Color3.fromRGB(134, 38, 38),
        ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
        ["From"] = "Moosewood"
    },
    ["Precision Rod"] = {
        ["Price"] = (1 / 0),
        ["Description"] = "Counterpart to rapid rod, with much better resilience!",
        ["Luck"] = 150,
        ["LureSpeed"] = 80,
        ["Strength"] = 12000,
        ["LineDistance"] = 100,
        ["Resilience"] = 5,
        ["Control"] = 0,
        ["Color"] = Color3.fromRGB(154, 170, 190),
        ["BobberTop"] = Color3.fromRGB(134, 38, 38),
        ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
        ["Unpurchasable"] = true
    },
    ["Plastic Rod"] = {
        ["Price"] = 900,
        ["Description"] = "Made of ABS plastic; You can trust this rod will last you.",
        ["Luck"] = 15,
        ["LureSpeed"] = 90,
        ["Strength"] = 100,
        ["LineDistance"] = 15,
        ["Resilience"] = 10,
        ["Control"] = 0,
        ["Color"] = Color3.fromRGB(73, 240, 255),
        ["BobberTop"] = Color3.fromRGB(163, 60, 60),
        ["BobberBottom"] = Color3.fromRGB(255, 242, 93),
        ["From"] = "Moosewood"
    },
    ["Carbon Rod"] = {
        ["Price"] = 2000,
        ["Description"] = "Stiff, strong, and easier to handle than other rods out there, however it is slightly shorter.",
        ["Luck"] = 25,
        ["LureSpeed"] = 110,
        ["Strength"] = 600,
        ["LineDistance"] = 15,
        ["Resilience"] = 10,
        ["Control"] = 0.05,
        ["Color"] = Color3.fromRGB(155, 190, 255),
        ["BobberTop"] = Color3.fromRGB(69, 109, 117),
        ["BobberBottom"] = Color3.fromRGB(192, 233, 255),
        ["From"] = "Moosewood"
    },
    ["Long Rod"] = {
        ["Price"] = 4500,
        ["Description"] = "Not the strongest, but it\226\128\153s sure the longest! Is this really needed?",
        ["Luck"] = 30,
        ["LureSpeed"] = 80,
        ["Strength"] = 250,
        ["LineDistance"] = 300,
        ["Resilience"] = 0,
        ["Control"] = -0.1,
        ["Color"] = Color3.fromRGB(220, 204, 167),
        ["BobberTop"] = Color3.fromRGB(134, 38, 38),
        ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
    },
    ["Executive Rod"] = {
        ["Price"] = (1 / 0),
        ["Description"] = "Game development is truly difficult..",
        ["Luck"] = 0,
        ["LureSpeed"] = 1,
        ["Strength"] = (1 / 0),
        ["LineDistance"] = 100,
        ["Resilience"] = 0,
        ["Control"] = 0.4,
        ["Color"] = Color3.fromRGB(255, 42, 42),
        ["BobberTop"] = Color3.fromRGB(255, 0, 0),
        ["BobberBottom"] = Color3.fromRGB(39, 39, 39),
        ["Unregistered"] = true,
        ["Unpurchasable"] = true
    },
    ["No-Life Rod"] = {
        ["Price"] = (1 / 0),
        ["Description"] = "Fisching 24/7/365. Are you okay?",
        ["Luck"] = 105,
        ["LureSpeed"] = 10,
        ["Strength"] = (1 / 0),
        ["LineDistance"] = 100,
        ["Resilience"] = 10,
        ["Control"] = 0.23,
        ["Color"] = Color3.fromRGB(255, 42, 42),
        ["BobberTop"] = Color3.fromRGB(255, 0, 0),
        ["BobberBottom"] = Color3.fromRGB(39, 39, 39),
        ["Unregistered"] = true,
        ["DEV"] = true,
        ["Unpurchasable"] = true
    },
    ["Seraphic Rod"] = {
        ["Price"] = (1 / 0),
        ["Description"] = "TOUCH SOME GRASS BUDDY",
        ["Luck"] = 150,
        ["LureSpeed"] = 5,
        ["Strength"] = (1 / 0),
        ["LineDistance"] = 130,
        ["Resilience"] = 20,
        ["Control"] = 0.25,
        ["Color"] = Color3.fromRGB(255, 170, 0),
        ["BobberTop"] = Color3.fromRGB(255, 204, 0),
        ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
        ["Unregistered"] = true,
        ["DEV"] = true,
        ["Unpurchasable"] = true
    }
}
local v2 = {
    ["Passive"] = "ShadowEntity",
    ["Requiriments"] = {
        ["GatesOpened"] = { "TheDepthsGate", "TheDepthsMazeGate" }
    },
    ["Price"] = 750000,
    ["Description"] = "\t\t\tThis Rod was crafted by the Legendary King of The Depths...\n\t\t\tLegends say, every once in a while the Spirit of the King visits you to hand you a gift from the deep waters!\n\t\t",
    ["Luck"] = 130,
    ["LureSpeed"] = 35,
    ["Strength"] = 30000,
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(255, 66, 52),
    ["BobberTop"] = Color3.fromRGB(255, 79, 66),
    ["BobberBottom"] = Color3.fromRGB(106, 26, 20),
    ["From"] = "The Depths"
}
v1["Rod Of The Depths"] = v2
v1["Evil Pitchfork of Doom Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "I\'m a witch and I\'m evil",
    ["Luck"] = 0,
    ["LureSpeed"] = 1,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 30,
    ["Control"] = 0.4,
    ["Color"] = Color3.fromRGB(189, 0, 0),
    ["BobberTop"] = Color3.fromRGB(167, 0, 0),
    ["BobberBottom"] = Color3.fromRGB(47, 0, 0),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Abyssal Spinecaster"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tTransformed from the spine of an ancient, unnatural being.\n\t\t\tBrimming with an enigmatic aura, its glowing spikes attract the most elusive fishes. [For @nekoanims]\n\t\t",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(88, 50, 170),
    ["BobberTop"] = Color3.fromRGB(215, 197, 154),
    ["BobberBottom"] = Color3.fromRGB(19, 11, 47),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Tetra Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A rod that belongs to the hands of the Tetrapede. [For @voaj77]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(170, 31, 26),
    ["BobberTop"] = Color3.fromRGB(255, 205, 26),
    ["BobberBottom"] = Color3.fromRGB(86, 0, 0),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Pen Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "zoo wee mama! [For @ZooWeeMamaMoment]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(85, 85, 85),
    ["BobberTop"] = Color3.fromRGB(98, 98, 98),
    ["BobberBottom"] = Color3.fromRGB(17, 17, 17),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Electric Guitar"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "In courtesy of Mila [For @kwijt]",
    ["Luck"] = 777,
    ["LureSpeed"] = -677,
    ["Strength"] = 777777777,
    ["LineDistance"] = 777,
    ["Resilience"] = 777,
    ["Control"] = 0.7,
    ["Color"] = Color3.fromRGB(106, 27, 27),
    ["BobberTop"] = Color3.fromRGB(124, 117, 114),
    ["BobberBottom"] = Color3.fromRGB(62, 24, 20),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Mila\'s Wand Of Magic"] = {
    ["Passive"] = "CatEntity",
    ["Price"] = (1 / 0),
    ["Description"] = "A purr-fectly made rod, hand-crafted by the Mila Appreciation Club. [For @kwijt]",
    ["Luck"] = 188,
    ["LureSpeed"] = 1,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 135,
    ["Resilience"] = 0,
    ["Control"] = 0.7,
    ["Color"] = Color3.fromRGB(244, 212, 185),
    ["BobberTop"] = Color3.fromRGB(255, 255, 255),
    ["BobberBottom"] = Color3.fromRGB(255, 189, 135),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Clickbait Caster"] = {
    ["Passive"] = "ContentCreatorEntity",
    ["Price"] = (1 / 0),
    ["Description"] = "Lights, camera, action\226\128\148now bite already! [CC Only]",
    ["Luck"] = 225,
    ["LureSpeed"] = 50,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 70,
    ["Resilience"] = 30,
    ["Control"] = 0.25,
    ["Color"] = Color3.fromRGB(255, 0, 0),
    ["BobberTop"] = Color3.fromRGB(0, 0, 0),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["???"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "a hot, presumably super-sharp blade of energy [Admin Rod, for @yvlyf]",
    ["Luck"] = 150,
    ["LureSpeed"] = 20,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 125,
    ["Resilience"] = 40,
    ["Control"] = 0.35,
    ["Color"] = Color3.fromRGB(106, 27, 27),
    ["BobberTop"] = Color3.fromRGB(124, 117, 114),
    ["BobberBottom"] = Color3.fromRGB(62, 14, 14),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1.ReRod = {
    ["Passive"] = "ReRod",
    ["Price"] = (1 / 0),
    ["Description"] = "my mom keeps calling me ReRod :d [For @RoReddo]",
    ["Luck"] = 2525,
    ["LureSpeed"] = -2425,
    ["Strength"] = 2525252525,
    ["LineDistance"] = 252,
    ["Resilience"] = 25.25252525,
    ["Control"] = 0.25,
    ["Color"] = Color3.fromRGB(238, 0, 4),
    ["BobberTop"] = Color3.fromRGB(255, 0, 0),
    ["BobberBottom"] = Color3.fromRGB(39, 39, 39),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Sovereign Doombringer"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Obliterate fish with a huge hammer. [Developer-Exclusive]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(137, 198, 255),
    ["BobberTop"] = Color3.fromRGB(151, 184, 255),
    ["BobberBottom"] = Color3.fromRGB(32, 37, 47),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Venomfang Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "From the bowels of an ancient temple. [For @kylecat11]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(96, 36, 131),
    ["BobberTop"] = Color3.fromRGB(107, 41, 148),
    ["BobberBottom"] = Color3.fromRGB(40, 15, 56),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["The Brick Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "It\'s real. [For @LiamGame09]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(128, 64, 255),
    ["BobberTop"] = Color3.fromRGB(255, 183, 38),
    ["BobberBottom"] = Color3.fromRGB(144, 11, 28),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1.CocoRod = {
    ["Price"] = (1 / 0),
    ["Description"] = "The Coco-nut-nut is a giant nut. [For @Goober_ish]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(72, 52, 42),
    ["BobberTop"] = Color3.fromRGB(255, 0, 0),
    ["BobberBottom"] = Color3.fromRGB(0, 0, 255),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Prismatic Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Feel my unstoppable daggers! [For @moonysquared]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(101, 104, 148),
    ["BobberTop"] = Color3.fromRGB(134, 125, 195),
    ["BobberBottom"] = Color3.fromRGB(34, 31, 47),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Yin Yang Rod"] = {
    ["Passive"] = "ShadowEntity_CustomRig_2",
    ["Price"] = (1 / 0),
    ["Description"] = "A battle with peace is though so everlasting. [For @robloxiandemo]",
    ["Luck"] = 375,
    ["LureSpeed"] = -50,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 125,
    ["Resilience"] = 75,
    ["Control"] = 0.7,
    ["Color"] = Color3.fromRGB(255, 255, 255),
    ["BobberTop"] = Color3.fromRGB(255, 255, 255),
    ["BobberBottom"] = Color3.fromRGB(0, 0, 0),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Fabulous Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Wheres the Primordial Wyrm? [For @GreenResolve]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(255, 134, 152),
    ["BobberTop"] = Color3.fromRGB(255, 192, 67),
    ["BobberBottom"] = Color3.fromRGB(56, 31, 36),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Katana Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Good at cutting fruit. [Developer-Exclusive]",
    ["Luck"] = 150,
    ["LureSpeed"] = 35,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(177, 177, 177),
    ["BobberTop"] = Color3.fromRGB(197, 197, 197),
    ["BobberBottom"] = Color3.fromRGB(48, 48, 48),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Rex Umbrarum"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Beeg Heavy Sord [For @Plutoly]",
    ["Luck"] = 150,
    ["LureSpeed"] = 1,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0.35,
    ["Color"] = Color3.fromRGB(100, 9, 18),
    ["BobberTop"] = Color3.fromRGB(159, 160, 162),
    ["BobberBottom"] = Color3.fromRGB(32, 32, 34),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Training Rod"] = {
    ["Price"] = 300,
    ["Description"] = "Handy fishing rod for honing your fishing skills. Remember, stay calm.",
    ["Luck"] = -70,
    ["LureSpeed"] = 90,
    ["Strength"] = 9,
    ["LineDistance"] = 20,
    ["Resilience"] = 20,
    ["Control"] = 0.2,
    ["Color"] = Color3.fromRGB(100, 198, 207),
    ["BobberTop"] = Color3.fromRGB(115, 199, 255),
    ["BobberBottom"] = Color3.fromRGB(50, 50, 50)
}
v1["Fast Rod"] = {
    ["Price"] = 4500,
    ["Description"] = "Quick rod that seems to catch fish in a fly! You can tell it\'s fast from the racing stripes.",
    ["Luck"] = -15,
    ["LureSpeed"] = 55,
    ["Strength"] = 175,
    ["LineDistance"] = 20,
    ["Resilience"] = -12,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(255, 101, 101),
    ["BobberTop"] = Color3.fromRGB(255, 103, 103),
    ["BobberBottom"] = Color3.fromRGB(255, 105, 105),
    ["From"] = "Moosewood"
}
v1["Lucky Rod"] = {
    ["Price"] = 5250,
    ["Description"] = "Seems to attract a handful of rare fish. Not sure why?.. Maybe I should buy a lottery ticket?",
    ["Luck"] = 60,
    ["LureSpeed"] = 130,
    ["Strength"] = 175,
    ["LineDistance"] = 20,
    ["Resilience"] = -12,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(188, 255, 190),
    ["BobberTop"] = Color3.fromRGB(80, 134, 80),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
    ["From"] = "Moosewood"
}
v1["Steady Rod"] = {
    ["Price"] = 7000,
    ["Description"] = "Insanely stiff and strong. Can withstand immense pressure and tension.- Increases shake UI size.",
    ["Luck"] = 35,
    ["LureSpeed"] = 160,
    ["Strength"] = 100000,
    ["LineDistance"] = 25,
    ["Resilience"] = 30,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(255, 190, 160),
    ["BobberTop"] = Color3.fromRGB(85, 85, 85),
    ["BobberBottom"] = Color3.fromRGB(95, 95, 95),
    ["From"] = "Roslit"
}
v1["Fortune Rod"] = {
    ["Price"] = 12750,
    ["Description"] = "Extremely lucky rod with an odd tendency to attract significantly rarer fish than usual.",
    ["Luck"] = 110,
    ["LureSpeed"] = 135,
    ["Strength"] = 700,
    ["LineDistance"] = 20,
    ["Resilience"] = -15,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(109, 77, 212),
    ["BobberTop"] = Color3.fromRGB(83, 56, 120),
    ["BobberBottom"] = Color3.fromRGB(255, 233, 111),
    ["From"] = "Roslit"
}
v1["Magma Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Hot to the touch. Engulfed with constantly burning passion to fish. [Capable of fishing in lava]",
    ["Luck"] = 15,
    ["LureSpeed"] = 170,
    ["Strength"] = 1200,
    ["LineDistance"] = 32,
    ["Resilience"] = 0,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(255, 122, 55),
    ["BobberTop"] = Color3.fromRGB(74, 41, 41),
    ["BobberBottom"] = Color3.fromRGB(33, 33, 33),
    ["Unpurchasable"] = true
}
v1["Reinforced Rod"] = {
    ["Price"] = 20000,
    ["Description"] = "Crafted by a metal stronger than diamond, making it capable of fishing in any harmful liquid.",
    ["Luck"] = 25,
    ["LureSpeed"] = 100,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 32,
    ["Resilience"] = 0,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(255, 178, 89),
    ["BobberTop"] = Color3.fromRGB(244, 152, 86),
    ["BobberBottom"] = Color3.fromRGB(39, 31, 25)
}
v1["Stone Rod"] = {
    ["Price"] = 3000,
    ["Description"] = "A rock-hard rod made purely from stone, which also makes it quite heavy.",
    ["Luck"] = 10,
    ["LureSpeed"] = 125,
    ["Strength"] = 900,
    ["LineDistance"] = 24,
    ["Resilience"] = 5,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(110, 110, 120),
    ["BobberTop"] = Color3.fromRGB(85, 85, 93),
    ["BobberBottom"] = Color3.fromRGB(32, 32, 35),
    ["From"] = "Ancient Isle"
}
v1["Phoenix Rod"] = {
    ["Price"] = 40000,
    ["Description"] = "Embued with the spirit of the graceful Phoenix. All fish have a 40% chance to be set ablaze.",
    ["Luck"] = 35,
    ["LureSpeed"] = 45,
    ["Strength"] = 4000,
    ["LineDistance"] = 20,
    ["Resilience"] = -10,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(255, 98, 87),
    ["BobberTop"] = Color3.fromRGB(234, 78, 255),
    ["BobberBottom"] = Color3.fromRGB(255, 116, 51),
    ["From"] = "Ancient Isle"
}
v1["Midas Rod"] = {
    ["Price"] = 55000,
    ["Description"] = "Blessed with the power of Midas. All fish have a 60% chance to be golden.",
    ["Luck"] = 10,
    ["LureSpeed"] = 40,
    ["Strength"] = 4000,
    ["LineDistance"] = 15,
    ["Resilience"] = -20,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(255, 226, 83),
    ["BobberTop"] = Color3.fromRGB(255, 184, 62),
    ["BobberBottom"] = Color3.fromRGB(255, 171, 53),
    ["From"] = "The Travelling Merchant"
}
v1["Trident Rod"] = {
    ["Price"] = 150000,
    ["Description"] = "\t\t\tWas originally the King of the Sea\'s way of defending his kingdom. All fish have a 30% chance to be atlantean.\n\t\t\t[Has a chance to stab a fish while catching it, briefly stunning it and increasing progress]\n\t\t",
    ["Luck"] = 150,
    ["LureSpeed"] = 80,
    ["Strength"] = 6000,
    ["LineDistance"] = 100,
    ["Resilience"] = 0,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(255, 191, 80),
    ["BobberTop"] = Color3.fromRGB(255, 178, 53),
    ["BobberBottom"] = Color3.fromRGB(255, 152, 48)
}
v1["Mythical Rod"] = {
    ["Price"] = 110000,
    ["Description"] = "Blessed with the power of The Keepers. All fish have a 30% chance to be rainbow.",
    ["Luck"] = 45,
    ["LureSpeed"] = 100,
    ["Strength"] = 2000,
    ["LineDistance"] = 20,
    ["Resilience"] = 0,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(255, 49, 159),
    ["BobberTop"] = Color3.fromRGB(255, 103, 156),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
    ["From"] = "The Travelling Merchant"
}
v1["Rapid Rod"] = {
    ["Price"] = 14000,
    ["Description"] = "Extremely fast rod that catches fish at record speeds! -It even has racing wings!",
    ["Luck"] = -20,
    ["LureSpeed"] = 28,
    ["Strength"] = 700,
    ["LineDistance"] = 21,
    ["Resilience"] = -20,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(255, 163, 87),
    ["BobberTop"] = Color3.fromRGB(255, 161, 94),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
    ["From"] = "Roslit"
}
v1["Brick Rod"] = {
    ["Price"] = 13337,
    ["Description"] = "Wait.. it\'s real?",
    ["Luck"] = 75,
    ["LureSpeed"] = 100,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 200,
    ["Resilience"] = 35,
    ["Control"] = 0.35,
    ["Color"] = Color3.fromRGB(245, 90, 90),
    ["BobberTop"] = Color3.fromRGB(245, 103, 103),
    ["BobberBottom"] = Color3.fromRGB(61, 35, 35)
}
v1["Magnet Rod"] = {
    ["Price"] = 15000,
    ["Description"] = "This rod has an advanced magnetic field, allowing it to quickly attract crates and loot.",
    ["Luck"] = 0,
    ["LureSpeed"] = 110,
    ["Strength"] = 10000,
    ["LineDistance"] = 21,
    ["Resilience"] = 0,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(0, 34, 255),
    ["BobberTop"] = Color3.fromRGB(255, 0, 0),
    ["BobberBottom"] = Color3.fromRGB(0, 17, 255),
    ["From"] = "Terrapin"
}
v1["Nocturnal Rod"] = {
    ["Price"] = 11000,
    ["Description"] = "Seems to wake up fish just by throwing the bobber in!-- Can catch nocturnal and diurnal fish at any time!",
    ["Luck"] = 70,
    ["LureSpeed"] = 110,
    ["Strength"] = 2000,
    ["LineDistance"] = 15,
    ["Resilience"] = 0,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(72, 59, 143),
    ["BobberTop"] = Color3.fromRGB(43, 41, 75),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
v1["Fungal Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "70% chance for the rod to sprout suspicious spores, giving you Luck IV for 45 seconds! Prettyy funky!",
    ["Luck"] = 45,
    ["LureSpeed"] = 110,
    ["Strength"] = 200,
    ["LineDistance"] = 15,
    ["Resilience"] = 0,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(78, 255, 78),
    ["BobberTop"] = Color3.fromRGB(51, 74, 45),
    ["BobberBottom"] = Color3.fromRGB(87, 109, 79)
}
v1["Destiny Rod"] = {
    ["Price"] = 190000,
    ["Description"] = "The Destiny Rod pulses continuously with the pure essence of luck. (5% Higher chance of Shiny & Sparkling fish)",
    ["Luck"] = 250,
    ["LureSpeed"] = 110,
    ["Strength"] = 10000,
    ["LineDistance"] = 25,
    ["Resilience"] = 0,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(255, 254, 220),
    ["BobberTop"] = Color3.fromRGB(248, 248, 248),
    ["BobberBottom"] = Color3.fromRGB(0, 0, 0),
    ["From"] = "Caleia"
}
v1["Haunted Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tOnly obtainable during FischFright;\n\t\t\tThe rod is cursed the constant energy of FischFright, allowing it to catch FischFright mutations all year around.\n\t\t",
    ["Luck"] = 50,
    ["LureSpeed"] = 100,
    ["Strength"] = 1000,
    ["LineDistance"] = 30,
    ["Resilience"] = 0,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(94, 255, 105),
    ["BobberTop"] = Color3.fromRGB(94, 255, 105),
    ["BobberBottom"] = Color3.fromRGB(18, 18, 18),
    ["Unpurchasable"] = true
}
v1["Kings Rod"] = {
    ["Price"] = 120000,
    ["Description"] = "All fish caught are 15% bigger.",
    ["Luck"] = 55,
    ["LureSpeed"] = 145,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 13,
    ["Resilience"] = 35,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(52, 96, 255),
    ["BobberTop"] = Color3.fromRGB(33, 111, 255),
    ["BobberBottom"] = Color3.fromRGB(35, 35, 35),
    ["From"] = "Keepers Altar"
}
v1["Aurora Rod"] = {
    ["Price"] = 90000,
    ["Description"] = "\t\t\tEnhanced by the Aurora Borealis\' energy. All fish have a 15% chance to have the Aurora mutation.\n\t\t\tChances increase during the Aurora Borealis.\n\t\t",
    ["Luck"] = 60,
    ["LureSpeed"] = 90,
    ["Strength"] = 6000,
    ["LineDistance"] = 20,
    ["Resilience"] = 6,
    ["Control"] = 0.06,
    ["Color"] = Color3.fromRGB(46, 255, 185),
    ["BobberTop"] = Color3.fromRGB(49, 255, 179),
    ["BobberBottom"] = Color3.fromRGB(107, 127, 255),
    ["From"] = "Vertigo"
}
v1["Sunken Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tAn ancient, coral-encrusted rod found in shipwreck depths, radiating faint power to lure rare fish.\n\t\t\tEvery 10 catches, gain a 25% higher chance to pull up a Treasure Map! All fish have a 5% chance to be Sunken.\n\t\t",
    ["Luck"] = 150,
    ["LureSpeed"] = 70,
    ["Strength"] = 5000,
    ["LineDistance"] = 60,
    ["Resilience"] = 15,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(145, 255, 115),
    ["BobberTop"] = Color3.fromRGB(162, 255, 134),
    ["BobberBottom"] = Color3.fromRGB(34, 53, 66),
    ["From"] = "Forsaken Shores",
    ["Unpurchasable"] = true
}
v1["Rod Of The Exalted One"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tOriginally created for the most magnificent royals, was lost in time and sealed away.\n\t\t\tExalted Relics now have a 2.5x higher chance to be caught.\n\t\t",
    ["Luck"] = 170,
    ["LureSpeed"] = 45,
    ["Strength"] = 70000,
    ["LineDistance"] = 70,
    ["Resilience"] = 20,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(255, 128, 249),
    ["BobberTop"] = Color3.fromRGB(148, 250, 255),
    ["BobberBottom"] = Color3.fromRGB(255, 124, 238),
    ["Unpurchasable"] = true
}
v1["Buddy Bond Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A friendly Rod!",
    ["Luck"] = 5,
    ["LureSpeed"] = 100,
    ["Strength"] = 300,
    ["LineDistance"] = 20,
    ["Resilience"] = 0,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(145, 255, 115),
    ["BobberTop"] = Color3.fromRGB(162, 255, 134),
    ["BobberBottom"] = Color3.fromRGB(34, 53, 66),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Ultratech Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tA rod of Unknown origin, feels pretty heavy. The rod has a pressed-in text on it\'s bottom which says \"Ultratech v.3.\"\n\t\t\tA scratched out name next to it which reads as: ZIK [For @Zik_isi].\n\t\t",
    ["Luck"] = 150,
    ["LureSpeed"] = 80,
    ["Strength"] = 10000,
    ["LineDistance"] = 100,
    ["Resilience"] = 10,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(245, 205, 48),
    ["BobberTop"] = Color3.fromRGB(245, 205, 48),
    ["BobberBottom"] = Color3.fromRGB(170, 0, 170),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Fischer\'s Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A fischer\'s starter rod to get started with Fisching! What else would you do with it?..",
    ["Luck"] = 10,
    ["LureSpeed"] = 90,
    ["Strength"] = 100,
    ["LineDistance"] = 20,
    ["Resilience"] = 5,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(245, 205, 48),
    ["BobberTop"] = Color3.fromRGB(245, 205, 48),
    ["BobberBottom"] = Color3.fromRGB(170, 0, 170),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Scurvy Rod"] = {
    ["Price"] = 50000,
    ["Description"] = "This rod has been on every pirate ship imaginable. Decent at everything, bad at nothing. Just like a pirate should!",
    ["Luck"] = 50,
    ["LureSpeed"] = 85,
    ["Strength"] = 2000,
    ["LineDistance"] = 20,
    ["Resilience"] = 15,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(245, 205, 48),
    ["BobberTop"] = Color3.fromRGB(245, 205, 48),
    ["BobberBottom"] = Color3.fromRGB(170, 0, 170),
    ["From"] = "Forsaken Shores"
}
local v3 = {
    ["Price"] = (1 / 0),
    ["Requiriments"] = {
        ["GatesOpened"] = { "RelicRodGate" }
    },
    ["Description"] = "\t\t\tA really old rod, found from the tombs of ancient isles, crafted out of ancient bone, but does it hold a mysterious power within it?\n\t\t",
    ["Luck"] = 25,
    ["LureSpeed"] = 80,
    ["Strength"] = 2500,
    ["LineDistance"] = 20,
    ["Resilience"] = 20,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(186, 178, 175),
    ["BobberTop"] = Color3.fromRGB(245, 213, 195),
    ["BobberBottom"] = Color3.fromRGB(133, 170, 158),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Relic Rod"] = v3
local v4 = {
    ["Price"] = (1 / 0),
    ["Requiriments"] = {
        ["GatesOpened"] = { "RelicRodGate" }
    },
    ["Description"] = "A rod forged with many valuable gemstones. Fish caught with this rod have a random sell value between 2-6x.",
    ["Luck"] = 25,
    ["LureSpeed"] = 80,
    ["Strength"] = 2500,
    ["LineDistance"] = 20,
    ["Resilience"] = 20,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(148, 19, 43),
    ["BobberTop"] = Color3.fromRGB(204, 52, 14),
    ["BobberBottom"] = Color3.fromRGB(81, 23, 13),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Auric Rod"] = v4
v1["Developers Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A rod made for developers not to have to suffer in fishing.",
    ["Luck"] = 150,
    ["LureSpeed"] = 99,
    ["Strength"] = 99999,
    ["LineDistance"] = 150,
    ["Resilience"] = 99,
    ["Control"] = 1,
    ["Color"] = Color3.fromRGB(255, 0, 0),
    ["BobberTop"] = Color3.fromRGB(245, 205, 48),
    ["BobberBottom"] = Color3.fromRGB(255, 0, 0),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Mystic Staff"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tA powerful staff once held by a mysterious witch who disappeared without a trace...\n\t\t\tStrangely, its magic seems to attract fish.\n\t\t",
    ["Luck"] = 100,
    ["LureSpeed"] = 1,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 30,
    ["Control"] = 0.4,
    ["Color"] = Color3.fromRGB(90, 255, 145),
    ["BobberTop"] = Color3.fromRGB(91, 36, 36),
    ["BobberBottom"] = Color3.fromRGB(188, 151, 100),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["The Twig"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "I think it genuinely may break in two. [WoozyNate Only]",
    ["Luck"] = 300,
    ["LureSpeed"] = 1,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 50,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(255, 255, 255),
    ["BobberTop"] = Color3.fromRGB(172, 172, 172),
    ["BobberBottom"] = Color3.fromRGB(59, 59, 59),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Nates Blade"] = {
    ["Passive"] = "ShadowEntity_CustomRig_1",
    ["Price"] = (1 / 0),
    ["Description"] = "A sword wielded by the oneand only Nate The human. Created by Nates father, out of Kee-Oths Blood.",
    ["Luck"] = 444,
    ["LureSpeed"] = 1,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 444,
    ["Resilience"] = 44,
    ["Control"] = 0.44,
    ["Color"] = Color3.fromRGB(255, 11, 11),
    ["BobberTop"] = Color3.fromRGB(255, 0, 0),
    ["BobberBottom"] = Color3.fromRGB(150, 15, 15),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Test Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Test Rod Description",
    ["Luck"] = 15,
    ["LureSpeed"] = 90,
    ["Strength"] = 100,
    ["LineDistance"] = 15,
    ["Resilience"] = 10,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(73, 240, 255),
    ["BobberTop"] = Color3.fromRGB(163, 60, 60),
    ["BobberBottom"] = Color3.fromRGB(255, 242, 93),
    ["Unregistered"] = true,
    ["DEV"] = true,
    ["Unpurchasable"] = true
}
v1["Voyager Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tA rod forged by an ancient civilization, capable of mass destruction. All fish have a 25% chance to be fossilized.\n\t\t\t[Lasers fish with an orbital cannon].\n\t\t",
    ["Luck"] = 85,
    ["LureSpeed"] = 75,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 60,
    ["Resilience"] = 10,
    ["Control"] = 0,
    ["Color"] = Color3.fromRGB(204, 181, 255),
    ["BobberTop"] = Color3.fromRGB(255, 178, 53),
    ["BobberBottom"] = Color3.fromRGB(228, 202, 235),
    ["Unpurchasable"] = true
}
v1["Rod Of The Forgotten Fang"] = {
    ["Passive"] = "Shark",
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tAfter 3 perfect catches, triggers a special mode where a Meg jumps out of the Deeps with a higher-tier fish.\n\t\t\tBoasting a 15-20% size buff.\n\t\t",
    ["Luck"] = 145,
    ["LureSpeed"] = 22,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 100,
    ["Resilience"] = 25,
    ["Control"] = 0.22,
    ["Color"] = Color3.fromRGB(49, 155, 255),
    ["BobberTop"] = Color3.fromRGB(228, 244, 255),
    ["BobberBottom"] = Color3.fromRGB(39, 59, 124),
    ["Unpurchasable"] = true
}
v1["Rod Of The Eternal King"] = {
    ["Passive"] = "RoyalEscort",
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tEvery 30 seconds, a 10% chance summons a \'Royal Escort\', boosting luck by 150% for 10 seconds.\n\t\t\tIf you miss a catch, there\'s a 15% chance of immediately catching a higher rarity fish. All fish have a 20% chance to be Greedy.\n\t\t",
    ["Luck"] = 160,
    ["LureSpeed"] = 50,
    ["Strength"] = 75000,
    ["LineDistance"] = 80,
    ["Resilience"] = 15,
    ["Control"] = 0.175,
    ["Color"] = Color3.fromRGB(255, 221, 25),
    ["BobberTop"] = Color3.fromRGB(255, 211, 33),
    ["BobberBottom"] = Color3.fromRGB(124, 72, 8),
    ["SplashSound"] = game:GetService("ReplicatedStorage").resources.sounds.sfx.fishing.customSplashes["Eternal King Splash"],
    ["Unpurchasable"] = true
}
v1["Resourceful Rod"] = {
    ["Passive"] = "2xBaits",
    ["Price"] = (1 / 0),
    ["Description"] = "Doubles the effects of all bait, enhancing your fishing experience and increasing the efficiency of every catch.",
    ["Luck"] = 20,
    ["LureSpeed"] = 85,
    ["Strength"] = 1000,
    ["LineDistance"] = 50,
    ["Resilience"] = 0,
    ["Control"] = -0.01,
    ["Color"] = Color3.fromRGB(255, 75, 15),
    ["BobberTop"] = Color3.fromRGB(255, 211, 33),
    ["BobberBottom"] = Color3.fromRGB(124, 72, 8),
    ["Unpurchasable"] = true
}
v1["Seasons Rod"] = {
    ["Passive"] = "Seasons",
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tBoosts fish luck by 20% for the current season.\n\t\t\tIt may also grant a \"Seasonal\" mutation that changes the fish\'s colors based on the season it was caught.\n\n\t\t\tSeasonal Mutation Buffs -> Winter: 2.5x Sell Price,  Summer: +25% Size, Spring: 3x Sell Price",
    ["Luck"] = 35,
    ["LureSpeed"] = 80,
    ["Strength"] = 4000,
    ["LineDistance"] = 50,
    ["Resilience"] = 10,
    ["Control"] = 0.03,
    ["Color"] = Color3.fromRGB(255, 185, 115),
    ["BobberTop"] = Color3.fromRGB(255, 211, 33),
    ["BobberBottom"] = Color3.fromRGB(124, 72, 8),
    ["Unpurchasable"] = true
}
v1["Wisdom Rod"] = {
    ["Passive"] = "WisdomPassive",
    ["Price"] = (1 / 0),
    ["Description"] = "A mystical rod that rewards consecutive catches, granting a 70-100% XP bonus after 5 successful catches in a row.",
    ["Luck"] = 35,
    ["LureSpeed"] = 90,
    ["Strength"] = 2000,
    ["LineDistance"] = 50,
    ["Resilience"] = 0,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(54, 47, 5),
    ["BobberTop"] = Color3.fromRGB(255, 211, 33),
    ["BobberBottom"] = Color3.fromRGB(124, 72, 8),
    ["Unpurchasable"] = true
}
v1["Celestial Rod"] = {
    ["Passive"] = "CelestialPower",
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tAfter catching 85 fish, summon Celestial powers for 5 minutes, boosting +50% luck, +30% lure speed.\n\t\t\tCaught fish also get the Celestial mutation & +30% XP on them!\n\t\t",
    ["Luck"] = 60,
    ["LureSpeed"] = 65,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 70,
    ["Resilience"] = 5,
    ["Control"] = 0.07,
    ["Color"] = Color3.fromRGB(19, 145, 255),
    ["BobberTop"] = Color3.fromRGB(58, 134, 255),
    ["BobberBottom"] = Color3.fromRGB(43, 208, 189),
    ["Unpurchasable"] = true
}
v1["The Lost Rod"] = {
    ["Passive"] = "PerfectCatch",
    ["Price"] = (1 / 0),
    ["Description"] = "After 6 Perfect Catches in a row, it triggers a special mode that boosts the rod\'s Luck by 150% for the next 3 casts.",
    ["Luck"] = 25,
    ["LureSpeed"] = 85,
    ["Strength"] = 55000,
    ["LineDistance"] = 70,
    ["Resilience"] = 8,
    ["Control"] = 0.08,
    ["Color"] = Color3.fromRGB(64, 255, 102),
    ["BobberTop"] = Color3.fromRGB(255, 211, 33),
    ["BobberBottom"] = Color3.fromRGB(124, 72, 8),
    ["Unpurchasable"] = true
}
v1["Riptide Rod"] = {
    ["Passive"] = "HighTide",
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tThe Riptide Rod fills its Tide Meter by 20% with each Perfect Catch.\n\t\t\tAt max, it enters `High Tide` for 3 casts, boosting rarity chance by 30% and bite speed by 25%.\n\t\t",
    ["Luck"] = 25,
    ["LureSpeed"] = 80,
    ["Strength"] = 3500,
    ["LineDistance"] = 50,
    ["Resilience"] = 5,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(66, 94, 255),
    ["BobberTop"] = Color3.fromRGB(255, 211, 33),
    ["BobberBottom"] = Color3.fromRGB(124, 72, 8),
    ["Unpurchasable"] = true
}
v1["Astral Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "\t\t\tAn intergalactic rod, powered by the harmonious essence of all the stars in the night sky.\n\t\t\tAll fish have a 5% chance to be Lunar.\n\t\t",
    ["Luck"] = 30,
    ["LureSpeed"] = 90,
    ["Strength"] = 1000,
    ["LineDistance"] = 20,
    ["Resilience"] = 5,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(105, 26, 241),
    ["BobberTop"] = Color3.fromRGB(98, 25, 255),
    ["BobberBottom"] = Color3.fromRGB(255, 155, 83),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Event Horizon Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "The powerful black hole within this rod decimates everything that in its path. All fish have a 5% chance to be Lunar.",
    ["Luck"] = 30,
    ["LureSpeed"] = 90,
    ["Strength"] = 1000,
    ["LineDistance"] = 20,
    ["Resilience"] = 5,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(255, 184, 5),
    ["BobberTop"] = Color3.fromRGB(255, 138, 5),
    ["BobberBottom"] = Color3.fromRGB(23, 23, 31),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Antler Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A rod bearing the magnificent antlers of a reindeer. All fish have a 25% chance to be Jolly.",
    ["Luck"] = 45,
    ["LureSpeed"] = 75,
    ["Strength"] = 200,
    ["LineDistance"] = 24,
    ["Resilience"] = -4,
    ["Control"] = 0.02,
    ["Color"] = Color3.fromRGB(140, 98, 86),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(122, 46, 46),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["North-Star Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "Powered by the intensely bright shine of the Northern Star.",
    ["Luck"] = 30,
    ["LureSpeed"] = 95,
    ["Strength"] = 875,
    ["LineDistance"] = 19,
    ["Resilience"] = 12,
    ["Control"] = 0.04,
    ["Color"] = Color3.fromRGB(255, 237, 170),
    ["BobberTop"] = Color3.fromRGB(195, 179, 117),
    ["BobberBottom"] = Color3.fromRGB(255, 209, 102),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Candy Cane Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A sweet and minty rod with a festive pattern. All fish have a 10% chance to be Festive.",
    ["Luck"] = 25,
    ["LureSpeed"] = 90,
    ["Strength"] = 150,
    ["LineDistance"] = 14,
    ["Resilience"] = -2,
    ["Control"] = 0.01,
    ["Color"] = Color3.fromRGB(185, 37, 37),
    ["BobberTop"] = Color3.fromRGB(230, 23, 23),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Krampus\'s Rod"] = {
    ["Passive"] = "Krampus",
    ["Price"] = (1 / 0),
    ["Description"] = "Haunted with the evil spirit of Krampus himself. Every 10 catches, gain a random temporary buff.",
    ["Luck"] = 15,
    ["LureSpeed"] = 70,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 40,
    ["Resilience"] = 8,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(255, 66, 91),
    ["BobberTop"] = Color3.fromRGB(241, 80, 96),
    ["BobberBottom"] = Color3.fromRGB(29, 30, 35),
    ["Unpurchasable"] = true,
    ["Unregistered"] = true
}
v1["Frostbane Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "An unwiedly sword, chilled throughout its blade by frost magic.",
    ["Luck"] = 45,
    ["LureSpeed"] = 90,
    ["Strength"] = 1500,
    ["LineDistance"] = 22,
    ["Resilience"] = 15,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(144, 240, 255),
    ["BobberTop"] = Color3.fromRGB(155, 242, 255),
    ["BobberBottom"] = Color3.fromRGB(48, 51, 62),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Frost Warden Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A frigid rod wielded by fierce anglers. Built to fish in the coldest of waters.",
    ["Luck"] = 45,
    ["LureSpeed"] = 90,
    ["Strength"] = 2200,
    ["LineDistance"] = 22,
    ["Resilience"] = 15,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(144, 240, 255),
    ["BobberTop"] = Color3.fromRGB(155, 242, 255),
    ["BobberBottom"] = Color3.fromRGB(48, 51, 62),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Crystalized Rod"] = {
    ["Passive"] = "Crystalized",
    ["Price"] = 35000,
    ["Description"] = "A luminous rod with a bright yellow glow and crystal-like effects.",
    ["Luck"] = 45,
    ["LureSpeed"] = 65,
    ["Strength"] = 25000,
    ["LineDistance"] = 100,
    ["Resilience"] = 15,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(154, 170, 190),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
v1["Ice Warpers Rod"] = {
    ["Passive"] = "IceWarpers",
    ["Price"] = 65000,
    ["Description"] = "A frost-themed rod with glowing blue accents and icy particle effects.",
    ["Luck"] = 60,
    ["LureSpeed"] = 50,
    ["Strength"] = 75000,
    ["LineDistance"] = 70,
    ["Resilience"] = 20,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(154, 170, 190),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
local v5 = {
    ["Passive"] = "HeavenRod",
    ["Requiriments"] = {
        ["GatesOpened"] = { "NorthFinalPuzzleDoor" }
    },
    ["Price"] = 1750000,
    ["Description"] = "A heavenly rod with glowing floating parts and a divine halo, emitting mythical particles and celestial animations.",
    ["Luck"] = 225,
    ["LureSpeed"] = 70,
    ["Strength"] = (1 / 0),
    ["LineDistance"] = 70,
    ["Resilience"] = 30,
    ["Control"] = 0.2,
    ["Color"] = Color3.fromRGB(190, 140, 24),
    ["BobberTop"] = Color3.fromRGB(234, 90, 23),
    ["BobberBottom"] = Color3.fromRGB(255, 159, 24)
}
v1["Heaven\'s Rod"] = v5
v1["Arctic Rod"] = {
    ["Price"] = 25000,
    ["Description"] = "A white rod with frost effects and a cool blue glow.",
    ["Luck"] = 65,
    ["LureSpeed"] = 55,
    ["Strength"] = 80000,
    ["LineDistance"] = 70,
    ["Resilience"] = 15,
    ["Control"] = 0.18,
    ["Color"] = Color3.fromRGB(154, 170, 190),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
v1["Avalanche Rod"] = {
    ["Price"] = 35000,
    ["Description"] = "A sleek rod with an icy blue spiral design and glowing blue accents.",
    ["Luck"] = 68,
    ["LureSpeed"] = 60,
    ["Strength"] = 65000,
    ["LineDistance"] = 70,
    ["Resilience"] = 10,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(154, 170, 190),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
v1["Summit Rod"] = {
    ["Price"] = 300000,
    ["Description"] = "A refined rod with snow-white highlights and shimmering blue effects.",
    ["Luck"] = 75,
    ["LureSpeed"] = 85,
    ["Strength"] = 200000,
    ["LineDistance"] = 70,
    ["Resilience"] = 15,
    ["Control"] = 0.25,
    ["Color"] = Color3.fromRGB(154, 170, 190),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
v1["Fischmas Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A festive fishing rod wrapped in holiday cheer, perfect for reeling in seasonal treasures.",
    ["Luck"] = 45,
    ["LureSpeed"] = 90,
    ["Strength"] = 2200,
    ["LineDistance"] = 22,
    ["Resilience"] = 15,
    ["Control"] = 0.05,
    ["Color"] = Color3.fromRGB(144, 240, 255),
    ["BobberTop"] = Color3.fromRGB(155, 242, 255),
    ["BobberBottom"] = Color3.fromRGB(48, 51, 62),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Frostfire Rod"] = {
    ["Price"] = (1 / 0),
    ["Description"] = "A sleek fishing rod wreathed in flames and frost, designed to tackle the toughest catches with elemental flair.",
    ["Luck"] = 35,
    ["LureSpeed"] = 80,
    ["Strength"] = 2200,
    ["LineDistance"] = 22,
    ["Resilience"] = 12,
    ["Control"] = 0.08,
    ["Color"] = Color3.fromRGB(144, 240, 255),
    ["BobberTop"] = Color3.fromRGB(155, 242, 255),
    ["BobberBottom"] = Color3.fromRGB(48, 51, 62),
    ["Unregistered"] = true,
    ["Unpurchasable"] = true
}
v1["Firework Rod"] = {
    ["Passive"] = "FireworkRod",
    ["Price"] = 35000,
    ["Description"] = "\t\t\tA rod imbued with festive magic. 15% chance for Firework Mutation (3.5x sell price).\n\t\t\tReduces whale progress speed by 20% and gives a +0.2% whale encounter rate.\n\t\t",
    ["Luck"] = 45,
    ["LureSpeed"] = 65,
    ["Strength"] = 25000,
    ["LineDistance"] = 100,
    ["Resilience"] = 15,
    ["Control"] = 0.15,
    ["Color"] = Color3.fromRGB(154, 170, 190),
    ["BobberTop"] = Color3.fromRGB(134, 38, 38),
    ["BobberBottom"] = Color3.fromRGB(255, 255, 255)
}
return v1
