local v3 = {
    ["Watering Can"] = {
        ["GearName"] = "Watering Can",
        ["GearRarity"] = "Common",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://140223014467344",
    },
    ["Trading Ticket"] = {
        ["GearName"] = "Trading Ticket",
        ["GearRarity"] = "Uncommon",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://80065730540573",
    },
    ["Trowel"] = {
        ["GearName"] = "Trowel",
        ["GearRarity"] = "Uncommon",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://115261280019001",
    },
    ["Recall Wrench"] = {
        ["GearName"] = "Recall Wrench",
        ["GearRarity"] = "Uncommon",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://98327818593168",
    },
    ["Basic Sprinkler"] = {
        ["GearName"] = "Basic Sprinkler",
        ["GearRarity"] = "Rare",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://120314005864914",
    },
    ["Advanced Sprinkler"] = {
        ["GearName"] = "Advanced Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://90193997839883",
    },
    ["Small Toy"] = {
        ["GearName"] = "Small Toy",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://118990580091132",
    },
    ["Medium Toy"] = {
        ["GearName"] = "Medium Toy",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 3,
        ["Asset"] = "rbxassetid://87196351819335",
    },
    ["Small Treat"] = {
        ["GearName"] = "Small Treat",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://107646462537237",
    },
    ["Medium Treat"] = {
        ["GearName"] = "Medium Treat",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 3,
        ["Asset"] = "rbxassetid://134834545436849",
    },
    ["Godly Sprinkler"] = {
        ["GearName"] = "Godly Sprinkler",
        ["GearRarity"] = "Mythical",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://75442797836082",
    },
    ["Lightning Rod"] = {
        ["GearName"] = "Lightning Rod",
        ["GearRarity"] = "Mythical",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://125433095334047",
    },
    ["Magnifying Glass"] = {
        ["GearName"] = "Magnifying Glass",
        ["GearRarity"] = "Mythical",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://107914377975445",
    },
    ["Tanning Mirror"] = {
        ["GearName"] = "Tanning Mirror",
        ["GearRarity"] = "Mythical",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://81619835086288",
    },
    ["Master Sprinkler"] = {
        ["GearName"] = "Master Sprinkler",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://98504519094449",
    },
    ["Cleaning Spray"] = {
        ["GearName"] = "Cleaning Spray",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://134458369683392",
    },
    ["Silver Fertilizer"] = {
        ["GearName"] = "Silver Fertilizer",
        ["GearRarity"] = "Mythical",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://116180181854951",
    },
    ["Gold Fertilizer"] = {
        ["GearName"] = "Gold Fertilizer",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://136127365492823",
    },
    ["Rainbow Fertilizer"] = {
        ["GearName"] = "Rainbow Fertilizer",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://84184684687849",
    },
    ["Favorite Tool"] = {
        ["GearName"] = "Favorite Tool",
        ["GearRarity"] = "Divine",
        ["Stack"] = 20,
        ["Asset"] = "rbxassetid://129676033321965",
    },
    ["Harvest Tool"] = {
        ["GearName"] = "Harvest Tool",
        ["GearRarity"] = "Divine",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://99521037861537",
    },
    ["Friendship Pot"] = {
        ["GearName"] = "Friendship Pot",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://106888620308041",
    },
    ["Pet Pouch"] = {
        ["GearName"] = "Pet Pouch",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://81309368707861",
    },
    ["Grandmaster Sprinkler"] = {
        ["GearName"] = "Grandmaster Sprinkler",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://113979110147102",
    },
    ["Levelup Lollipop"] = {
        ["GearName"] = "Levelup Lollipop",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://92216660575982",
    },
    ["Silver Lollipop"] = {
        ["GearName"] = "Silver Lollipop",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://129355380203742",
    },
    ["Gold Lollipop"] = {
        ["GearName"] = "Gold Lollipop",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://88845732789842",
    },
    ["Rainbow Lollipop"] = {
        ["GearName"] = "Rainbow Lollipop",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://75150651893802",
    },
    ["Mega Lollipop"] = {
        ["GearName"] = "Mega Lollipop",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://91289591806628",
    },
    ["Event Lantern"] = {
        ["GearName"] = "Event Lantern",
        ["GearRarity"] = "Rare",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://120464955669662",
    },
    ["Small Bowl"] = {
        ["GearName"] = "Small Pet Size Boost",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://114089908282697",
    },
    ["Medium Bowl"] = {
        ["GearName"] = "Medium Pet Size Boost",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 3,
        ["Asset"] = "rbxassetid://127973837115000",
    },
    ["Garden Guide"] = {
        ["GearName"] = "Garden Guide",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://96147201616033",
    },
    ["Plant Booster"] = {
        ["GearName"] = "Plant Booster",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://86602672756084",
    },
    ["Pet Shard Tranquil"] = {
        ["GearName"] = "Pet Shard Tranquil",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://89240663276696",
    },
    ["Pet Shard Corrupted"] = {
        ["GearName"] = "Pet Shard Corrupted",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://114953192928342",
    },
    ["Pet Shard Fried"] = {
        ["GearName"] = "Pet Shard Fried",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://76156216865979",
    },
    ["Pet Shard Mega"] = {
        ["GearName"] = "Pet Shard Mega",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://132251713933337",
    },
    ["Pet Shard Aromatic"] = {
        ["GearName"] = "Pet Shard Aromatic",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://126438230205950",
    },
    ["Pet Shard Silver"] = {
        ["GearName"] = "Pet Shard Silver",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://121577824688085",
    },
    ["Pet Shard Golden"] = {
        ["GearName"] = "Pet Shard Golden",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://93203116407679",
    },
    ["Pet Shard Rainbow"] = {
        ["GearName"] = "Pet Shard Rainbow",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://103557510521587",
    },
    ["Cleansing Pet Shard"] = {
        ["GearName"] = "Cleansing Pet Shard",
        ["GearRarity"] = "Divine",
        ["StockChance"] = 12,
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://80815612016706",
    },
    ["Pet Shard GiantBean"] = {
        ["GearName"] = "Pet Shard GiantBean",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://99321086204906",
    },
    ["Pet Shard Glimmering"] = {
        ["GearName"] = "Pet Shard Glimmering",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://125506626001248",
    },
    ["Pet Shard Luminous"] = {
        ["GearName"] = "Pet Shard Luminous",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://125506626001248",
    },
    ["Tranquil Radar"] = {
        ["GearName"] = "Tranquil Radar",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://133779065360759",
    },
    ["Corrupt Radar"] = {
        ["GearName"] = "Corrupt Radar",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://101384658792701",
    },
    ["Glimmering Radar"] = {
        ["GearName"] = "Glimmering Radar",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://102770681711135",
    },
    ["Mutation Spray Choc"] = {
        ["GearName"] = "Mutation Spray Choc",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://104900539098874",
    },
    ["Mutation Spray Pollinated"] = {
        ["GearName"] = "Mutation Spray Choc",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://103170047234524",
    },
    ["Mutation Spray Shocked"] = {
        ["GearName"] = "Mutation Spray Shocked",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://131806798815295",
    },
    ["Mutation Spray Chilled"] = {
        ["GearName"] = "Mutation Spray Chilled",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://81133409755490",
    },
    ["Mutation Spray Glimmering"] = {
        ["GearName"] = "Mutation Spray Glimmering",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://121096078532314",
    },
    ["Mutation Spray Luminous"] = {
        ["GearName"] = "Mutation Spray Luminous",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://85780662842247",
    },
    ["Mutation Spray Burnt"] = {
        ["GearName"] = "Mutation Spray Burnt",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://99446610437201",
    },
    ["Mutation Spray Cooked"] = {
        ["GearName"] = "Mutation Spray Cooked",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://126432432084372",
    },
    ["Mutation Spray HoneyGlazed"] = {
        ["GearName"] = "Mutation Spray HoneyGlazed",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://82241706965782",
    },
    ["Mutation Spray Fried"] = {
        ["GearName"] = "Mutation Spray Fried",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://94750385791976",
    },
    ["Mutation Spray Cloudtouched"] = {
        ["GearName"] = "Mutation Spray Cloudtouched",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://83361659792737",
    },
    ["Mutation Spray Wet"] = {
        ["GearName"] = "Mutation Spray Wet",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://71256961970374",
    },
    ["Mutation Spray Windstruck"] = {
        ["GearName"] = "Mutation Spray Windstruck",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://108654127163609",
    },
    ["Mutation Spray Verdant"] = {
        ["GearName"] = "Mutation Spray Verdant",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://110872337408229",
    },
    ["Mutation Spray Disco"] = {
        ["GearName"] = "Mutation Spray Disco",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://101495928459631",
    },
    ["Mutation Spray Amber"] = {
        ["GearName"] = "Mutation Spray Amber",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://134185036315338",
    },
    ["Mutation Spray Corrupt"] = {
        ["GearName"] = "Mutation Spray Corrupt",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://131496625192449",
    },
    ["Mutation Spray Tranquil"] = {
        ["GearName"] = "Mutation Spray Tranquil",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://100842098233252",
    },
    ["Mutation Spray Bloom"] = {
        ["GearName"] = "Mutation Spray Bloom",
        ["GearRarity"] = "Divine",
        ["Stack"] = 10,
        ["Asset"] = "rbxassetid://104900539098874",
    },
    ["Reclaimer"] = {
        ["GearName"] = "Reclaimer",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://79034654924763",
    },
    ["Firework"] = {
        ["GearName"] = "Firework",
        ["GearRarity"] = "Common",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://106727369137782",
    },
    ["Beanworks"] = {
        ["GearName"] = "Beanworks",
        ["GearRarity"] = "Common",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://106727369137782",
    },
    ["Tropical Mist Sprinkler"] = {
        ["GearName"] = "Tropical Mist Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://122592465315585",
    },
    ["Spice Spritzer Sprinkler"] = {
        ["GearName"] = "Spice Spritzer Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://130541096369176",
    },
    ["Sweet Soaker Sprinkler"] = {
        ["GearName"] = "Sweet Soaker Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://91036428046936",
    },
    ["Stalk Sprout Sprinkler"] = {
        ["GearName"] = "Stalk Sprout Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://125326661954614",
    },
    ["Berry Blusher Sprinkler"] = {
        ["GearName"] = "Berry Blusher Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://121776369197466",
    },
    ["Flower Froster Sprinkler"] = {
        ["GearName"] = "Flower Froster Sprinkler",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://86602672756084",
    },
    ["Bean Speaker"] = {
        ["GearName"] = "Bean Speaker",
        ["GearRarity"] = "Common",
        ["Stack"] = 5,
        ["Asset"] = "rbxassetid://106727369137782",
    },
    ["Can Of Beans"] = {
        ["GearName"] = "Can Of Beans",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://75302189671253",
    },
    ["Fairy Summoner"] = {
        ["GearName"] = "Fairy Summoner",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://70923644117541",
    },
    ["Fairy Power Extender"] = {
        ["GearName"] = "Fairy Power Extender",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://124645530618939",
    },
    ["Fairy Targeter"] = {
        ["GearName"] = "Fairy Targeter",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://120586018702719",
    },
    ["Fairy Caller"] = {
        ["GearName"] = "Fairy Caller",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://91757592448950",
    },
    ["Luminous Wand"] = {
        ["GearName"] = "Luminous Wand",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://77498741936491",
    },
    ["Fairy Net"] = {
        ["GearName"] = "Fairy Net",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://116748151506209",
    },
    ["Fairy Jar"] = {
        ["GearName"] = "Fairy Jar",
        ["GearRarity"] = "Rare",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://96168603825271",
    },
    ["Pet Name Reroller"] = {
        ["GearName"] = "Pet Name Reroller",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://75965661010163",
    },
    ["Pet Lead"] = {
        ["GearName"] = "Pet Lead",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://129795023623532",
    },
    ["Chocolate Sprinkler"] = {
        ["GearName"] = "Chocolate Sprinkler",
        ["GearRarity"] = "Mythical",
        ["Asset"] = "rbxassetid://115881753102059",
        ["Stack"] = 1,
    },
    ["Nectar Staff"] = {
        ["GearName"] = "Nectar Staff",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://109105197997415",
    },
    ["Night Staff"] = {
        ["GearName"] = "Night Staff",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://86894493095285",
    },
    ["Tranquil Staff"] = {
        ["GearName"] = "Tranquil Staff",
        ["GearRarity"] = "Common",
        ["Asset"] = "rbxassetid://118265137979088",
    },
    ["Corrupt Staff"] = {
        ["GearName"] = "Corrupt Staff",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://133948006225272",
    },
    ["Star Caller"] = {
        ["GearName"] = "Star Caller",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://108537992961712",
    },
    ["Honey Sprinkler"] = {
        ["GearName"] = "Honey Sprinkler",
        ["GearRarity"] = "Divine",
        ["Asset"] = "rbxassetid://90156288104343",
        ["Stack"] = 1,
    },
    ["Pollen Radar"] = {
        ["GearName"] = "Pollen Radar",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://105620836609339",
    },
    ["Firefly Jar"] = {
        ["GearName"] = "Firefly Jar",
        ["GearRarity"] = "Rare",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://123147701320566",
    },
    ["Sky Lantern"] = {
        ["GearName"] = "Sky Lantern",
        ["GearRarity"] = "Uncommon",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://88840697754774",
    },
    ["Maple Leaf Kite"] = {
        ["GearName"] = "Maple Leaf Kite",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://94694559446067",
    },
    ["Leaf Blower"] = {
        ["GearName"] = "Leaf Blower",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://116067282320680",
    },
    ["Maple Syrup"] = {
        ["GearName"] = "Maple Syrup",
        ["GearRarity"] = "Legendary",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://82575496704431",
    },
    ["Maple Leaf Charm"] = {
        ["GearName"] = "Maple Leaf Charm",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://132566474931424",
    },
    ["Maple Sprinkler"] = {
        ["GearName"] = "Maple Sprinkler",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://96077151737465",
    },
    ["Bonfire"] = {
        ["GearName"] = "Bonfire",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://71754335799002",
    },
    ["Harvest Basket"] = {
        ["GearName"] = "Harvest Basket",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://90267962738984",
    },
    ["Golden Acorn"] = {
        ["GearName"] = "Golden Acorn",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://122041101537564",
    },
    ["Rake"] = {
        ["GearName"] = "Rake",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://123007566196057",
    },
    ["Sheckles Gun"] = {
        ["GearName"] = "Sheckles Gun",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://128722800183998",
    },
    ["Super Leaf Blower"] = {
        ["GearName"] = "Super Leaf Blower",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://115901959792916",
    },
    ["Acorn Bell"] = {
        ["GearName"] = "Acorn Bell",
        ["GearRarity"] = "Divine",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://109503976464120",
    },
    ["Acorn Lollipop"] = {
        ["GearName"] = "Acorn Lollipop",
        ["GearRarity"] = "Prismatic",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://114980305116277",
    },
    ["Grow All"] = {
        ["GearName"] = "Grow All",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://120928632087334",
    },
    ["Steal"] = {
        ["GearName"] = "Steal",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://71833009041293",
    },
    ["Super Watering Can"] = {
        ["GearName"] = "Super  Watering Can",
        ["GearRarity"] = "Common",
        ["Stack"] = 1,
        ["Asset"] = "rbxassetid://139084715000316",
    }
}
return v3
