local v16 = {
    ["Turnip"] = {
        ["SeedName"] = "Turnip",
        ["SeedRarity"] = "Common",
        ["StockChance"] = 1,
        ["StockAmount"] = { 5, 7 },
        ["Price"] = 10000000,
        ["PurchaseID"] = 3401533643,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 10,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 450]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 129
    },
    ["Parsley"] = {
        ["SeedName"] = "Parsley",
        ["SeedRarity"] = "Uncommon",
        ["StockChance"] = 3,
        ["StockAmount"] = { 3, 5 },
        ["Price"] = 20000000,
        ["PurchaseID"] = 3401533790,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 2 Times",
        ["LayoutOrder"] = 20,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 477]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 169
    },
    ["Meyer Lemon"] = {
        ["SeedName"] = "Meyer Lemon",
        ["SeedRarity"] = "Rare",
        ["StockChance"] = 4,
        ["StockAmount"] = { 1, 2 },
        ["Price"] = 50000000,
        ["PurchaseID"] = 3401533943,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 4 Times",
        ["LayoutOrder"] = 30,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 504]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 247
    },
    ["Carnival Pumpkin"] = {
        ["SeedName"] = "Carnival Pumpkin",
        ["SeedRarity"] = "Legendary",
        ["StockChance"] = 6,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 100000000,
        ["PurchaseID"] = 3401534101,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 5 Times",
        ["LayoutOrder"] = 40,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 531]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 479
    },
    ["Kniphofia"] = {
        ["SeedName"] = "Kniphofia",
        ["SeedRarity"] = "Mythical",
        ["StockChance"] = 18,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 450000000,
        ["PurchaseID"] = 3401534268,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 10 Times",
        ["LayoutOrder"] = 50,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 558]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 659
    },
    ["Golden Peach"] = {
        ["SeedName"] = "Golden Peach",
        ["SeedRarity"] = "Divine",
        ["StockChance"] = 30,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 900000000,
        ["PurchaseID"] = 3401534430,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 13 Times",
        ["LayoutOrder"] = 60,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 585]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 719
    },
    ["Maple Resin"] = {
        ["SeedName"] = "Maple Resin",
        ["SeedRarity"] = "Transcendent",
        ["StockChance"] = 60,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 1500000000,
        ["PurchaseID"] = 3401534643,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 17 Times",
        ["LayoutOrder"] = 70,
        ["ItemType"] = "Seed",
        ["Stack"] = 1,
        ["ShopIndex"] = 1,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 612]]
            return true
        end,
        ["Description"] = "",
        ["FallbackPrice"] = 999
    },
    ["Firefly Jar"] = {
        ["SeedName"] = "Firefly Jar",
        ["SeedRarity"] = "Common",
        ["StockChance"] = 1,
        ["StockAmount"] = { 5, 8 },
        ["Price"] = 500000,
        ["PurchaseID"] = 3401535051,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 10,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 634]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 37
    },
    ["Sky Lantern"] = {
        ["SeedName"] = "Sky Lantern",
        ["SeedRarity"] = "Uncommon",
        ["StockChance"] = 1,
        ["StockAmount"] = { 2, 4 },
        ["Price"] = 1000000,
        ["PurchaseID"] = 3401535228,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 20,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 658]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 39
    },
    ["Maple Leaf Kite"] = {
        ["SeedName"] = "Maple Leaf Kite",
        ["SeedRarity"] = "Uncommon",
        ["StockChance"] = 2,
        ["StockAmount"] = { 1, 3 },
        ["Price"] = 15000000,
        ["PurchaseID"] = 3401535375,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 30,
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 681]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 49
    },
    ["Leaf Blower"] = {
        ["SeedName"] = "Leaf Blower",
        ["SeedRarity"] = "Rare",
        ["StockChance"] = 3,
        ["StockAmount"] = { 1, 3 },
        ["Price"] = 35000000,
        ["PurchaseID"] = 3401535500,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 40,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 2 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 707]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 89
    },
    ["Maple Syrup"] = {
        ["SeedName"] = "Maple Syrup",
        ["SeedRarity"] = "Rare",
        ["StockChance"] = 1,
        ["StockAmount"] = { 2, 4 },
        ["Price"] = 50000000,
        ["PurchaseID"] = 3401535642,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 50,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 5 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 733]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 39
    },
    ["Maple Sprinkler"] = {
        ["SeedName"] = "Maple Sprinkler",
        ["SeedRarity"] = "Legendary",
        ["StockChance"] = 5,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 250000000,
        ["PurchaseID"] = 3401535950,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 60,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 9 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 759]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 189
    },
    ["Bonfire"] = {
        ["SeedName"] = "Bonfire",
        ["SeedRarity"] = "Mythical",
        ["StockChance"] = 8,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 500000000,
        ["PurchaseID"] = 3401536118,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 70,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 10 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 785]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 259
    },
    ["Harvest Basket"] = {
        ["SeedName"] = "Harvest Basket",
        ["SeedRarity"] = "Divine",
        ["StockChance"] = 15,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 750000000,
        ["PurchaseID"] = 3401536271,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 80,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 12 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 811]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 67
    },
    ["Maple Leaf Charm"] = {
        ["SeedName"] = "Maple Leaf Charm",
        ["SeedRarity"] = "Legendary",
        ["StockChance"] = 25,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 100000000,
        ["PurchaseID"] = 3401535789,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 90,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 13 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 837]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 195
    },
    ["Golden Acorn"] = {
        ["SeedName"] = "Golden Acorn",
        ["SeedRarity"] = "Prismatic",
        ["StockChance"] = 40,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 10000000000,
        ["PurchaseID"] = 3401536371,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 100,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 17 Times",
        ["CanBuy"] = function(_, _) --[[Function name: CanBuy, line 863]]
            return true
        end,
        ["ItemType"] = "Gear",
        ["Description"] = "",
        ["ShopIndex"] = 2,
        ["Stack"] = 1,
        ["FallbackPrice"] = 239
    },
    ["Fall Egg"] = {
        ["SeedName"] = "Fall Egg",
        ["SeedRarity"] = "Mythical",
        ["StockChance"] = 1,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 90000000,
        ["PurchaseID"] = 3401534851,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 440,
        ["ItemType"] = "Egg",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 3,
        ["FallbackPrice"] = 149
    },
    ["Chipmunk"] = {
        ["SeedName"] = "Chipmunk",
        ["SeedRarity"] = "Common",
        ["StockChance"] = 3,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 150000000,
        ["PurchaseID"] = 3401548923,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 450,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 4 Times",
        ["ItemType"] = "Pet",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 3,
        ["FallbackPrice"] = 299
    },
    ["Red Squirrel"] = {
        ["SeedName"] = "Red Squirrel",
        ["SeedRarity"] = "Rare",
        ["StockChance"] = 6,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 400000000,
        ["PurchaseID"] = 3401549019,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 460,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 7 Times",
        ["ItemType"] = "Pet",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 3,
        ["FallbackPrice"] = 219
    },
    ["Marmot"] = {
        ["SeedName"] = "Marmot",
        ["SeedRarity"] = "Legendary",
        ["StockChance"] = 12,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 700000000,
        ["PurchaseID"] = 3401537209,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 470,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 10 Times",
        ["ItemType"] = "Pet",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 3,
        ["FallbackPrice"] = 459
    },
    ["Sugar Glider"] = {
        ["SeedName"] = "Sugar Glider",
        ["SeedRarity"] = "Mythical",
        ["StockChance"] = 24,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 900000000,
        ["PurchaseID"] = 3401537342,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 480,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 13 Times",
        ["ItemType"] = "Pet",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 3,
        ["FallbackPrice"] = 568
    },
    ["Space Squirrel"] = {
        ["SeedName"] = "Space Squirrel",
        ["SeedRarity"] = "Divine",
        ["StockChance"] = 50,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 1250000000,
        ["PurchaseID"] = 3401549137,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 490,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 17 Times",
        ["ItemType"] = "Pet",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 3,
        ["FallbackPrice"] = 659
    },
    ["Fall Crate"] = {
        ["SeedName"] = "Fall Crate",
        ["SeedRarity"] = "Legendary",
        ["StockChance"] = 1,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 50000000,
        ["PurchaseID"] = 3401536497,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 1,
        ["ItemType"] = "Crate",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 4,
        ["FallbackPrice"] = 179
    },
    ["Fall Leaf Chair"] = {
        ["SeedName"] = "Fall Leaf Chair",
        ["SeedRarity"] = "Common",
        ["StockChance"] = 1,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 10000000,
        ["PurchaseID"] = 3401536663,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 10,
        ["ItemType"] = "Cosmetic",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 4,
        ["FallbackPrice"] = 79
    },
    ["Maple Flag"] = {
        ["SeedName"] = "Maple Flag",
        ["SeedRarity"] = "Rare",
        ["StockChance"] = 2,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 15000000,
        ["PurchaseID"] = 3401536754,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 20,
        ["ItemType"] = "Cosmetic",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 4,
        ["FallbackPrice"] = 119
    },
    ["Flying Kite"] = {
        ["SeedName"] = "Flying Kite",
        ["SeedRarity"] = "Legendary",
        ["StockChance"] = 3,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 25000000,
        ["PurchaseID"] = 3401536894,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 30,
        ["ItemType"] = "Cosmetic",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 4,
        ["FallbackPrice"] = 139
    },
    ["Fall Fountain"] = {
        ["SeedName"] = "Fall Fountain",
        ["SeedRarity"] = "Divine",
        ["StockChance"] = 30,
        ["StockAmount"] = { 1, 1 },
        ["Price"] = 1000000000,
        ["PurchaseID"] = 3401537019,
        ["DisplayInShop"] = true,
        ["ShowOdds"] = true,
        ["LayoutOrder"] = 40,
        ["LockedInShop"] = true,
        ["UnlockText"] = "Contribute to Fall Bloom 10 Times",
        ["ItemType"] = "Cosmetic",
        ["Stack"] = 1,
        ["Description"] = "",
        ["ShopIndex"] = 4,
        ["FallbackPrice"] = 279
    }
}
return v16
