return {
	Mutations = {
		"Shocked",
		"Twisted",
		"Wet",
		"Chilled",
		"Frozen",
		"Disco",
		"Choc",
		"Burnt",
		"Moonlit",
		"Bloodlit",
		"Voidtouched",
		"Pollinated",
		"Dawnbound",
		"Zombified",
		"HoneyGlazed",
		"Cooked",
		"Meteoric",
		"Celestial",
		"Heavenly",
		"Plasma",
		"Molten",
		"Windstruck",
		"Alienlike",
		"Galactic",
		"Sundried",
		"Verdant",
		"Paradisal"
	},
	Variants = {
		"Normal",
		"Gold",
		"Rainbow"
	},
	Teleports = {
		"Seeds Shop",
		"Sell Shop",
		"Gear Shop",
		"Cosmetics Shop",
		"Eggs Shop",
		"Event Area"
	},
	Recipes = {
		MiniWorkbench = {
			"Crafters Seed Pack",
			"Manuka Flower",
			"Dandelion",
			"Lumira",
			"Honeysuckle",
			"Bee Balm",
			"Nectar Thorn",
			"Suncoil"
		},
		LargeWorkbench = {
			"Tropical Mist Sprinkler",
			"Berry Blusher Sprinkler",
			"Spice Spritzer Sprinkler",
			"Sweet Soaker Sprinkler",
			"Flower Foster Sprinkler",
			"Stalk Sprout Sprinkler",
			"Mutation Spray Choc",
			"Mutation Spray Pollinated",
			"Honey Crafters Crate",
			"Anti Bee Egg",
			"Pack Bee"
		}
	},
	ServerEvents = {
		["Disco"] = "DiscoEvent",
		["Rain"] = "RainEvent",
		["Thunderstorm"] = "Thunderstorm",
		["Frost"] = "FrostEvent",
		["Scheckle Rain"] = "ScheckleRain",
		["Meteor Shower"] = "MeteorShower",
		["Chocolate Rain"] = "ChocolateRain",
		["Janzen Storm"] = "JanzenStorm",
		["DJ Jhai"] = "DJJhai",
		["Tornado"] = "TornadoEvent",
		["Black Hole"] = "Blackhole",
		["Jandel Float"] = "JandelFloat",
		["Killer Bunny????"] = "KillerBunny",
		["Space Travel"] = "SpaceTravelEvent",
		["Alien Invasion"] = "AlienInvasionEvent",
		["Gale"] = "Gale",
		["Heatwave"] = "HeatwaveEvent",
		["Jandel Laser"] = "JandelLazer",
		["Monster Mash"] = "MonsterMash",
		["Rainbow"] = "Rainbow",
		["Sun 'God'"] = "SunGod",
		["UnderTheSea"] = "UnderTheSea",
		["Volcano"] = "Volcano"
	},
	TeleportLocations = {
		["Garden"] = CFrame.new(0, 0, 0),
		["Seeds Shop"] = CFrame.new(62, 3, -27),
		["Sell Shop"] = CFrame.new(-259, 3, -9),
		["Gear Shop"] = CFrame.new(-285, 3, -33),
		["Cosmetics Shop"] = CFrame.new(-285, 3, -15),
		["Eggs Shop"] = CFrame.new(-284, 3, -2),
		["Event Area"] = CFrame.new(-101, 4, -7)
	},
	SummerFruits = {
		"Pineapple",
		"Watermelon",
		"Cauliflower",
		"Green Apple",
		"Banana",
		"Avocado",
		"Kiwi",
		"Avocado",
		"Prickly Pear",
		"Feijoa",
		"Sugar Apple",
		"Loquat",
		"Feijoa",
		"Wild Carrot",
		"Pear",
		"Cantaloupe",
		"Parasol Flower",
		"Rosy Delight",
		"Elephant Ears",
		"Bell Pepper"
	}

}
