return {
	Mutations = {"Eclipsed", "Meteoric", "Cyclonic", "Fried", "Drenched", "Tempestuous", "Shocked", "Aurora", "Choc", "Bloodlit", "Spaghetti", "Sliced", "Maelstrom", "Verdant", "Infected", "Enchanted", "Junkshock", "AncientAmber", "Twisted", "Alienlike", "FoxfireChakra", "CorruptChakra", "Cooked", "Chilled", "Heavenly", "Beanbound", "Radioactive", "Aromatic", "Boil", "Celestial", "Warped", "Windstruck", "Burnt", "Wet", "Gloom", "Meatball", "Jackpot", "Lightcycle", "Rot", "Subzero", "Friendbound", "Touchdown", "Paradisal", "Glitched", "Clay", "Amber", "Brainrot", "HoneyGlazed", "Frozen", "Corrupt", "OldAmber", "Bloom", "Fortune", "Cloudtouched", "Sandy", "Sauce", "Moonlit", "Oil", "Toxic", "Tranquil", "Enlightened", "Gnomed", "Chakra", "HarmonisedFoxfireChakra", "HarmonisedChakra", "Static", "CorruptFoxfireChakra", "Pasta", "Ceramic", "Plasma", "Molten", "Dawnbound", "Pollinated", "Wiltproof", "Zombified", "Disco", "Blitzshock", "Sundried", "Voidtouched", "Galactic", "Acidic"},
	CookingRecipes = {
		Soup = {
			"Carrot"
		},
		Sandwich = {
			"Tomato",
			"Corn"
		},
		Pie = {
			{
				"Pumpkin",
				"Apple"
			},
			{
				"Corn",
				"Coconut"
			}
		},
		Burger = {
			"Pepper",
			"Corn",
			"Tomato"
		},
		Hotdog = {
			"Pepper",
			{
				"Corn",
				"Banana"
			} 
		},
		Waffle = {
			{
				"Pumpkin",
				"Watermelon"
			},
			{
				"Pumpkin",
				"Sugar Apple"
			}
		},
		Salad = {
			"Tomato"
		},
		Sushi = {
			"Bamboo",
			"Corn"
		},
		IceCream = {
			{
				"Blueberry",
				"Corn"
			},
			{
				"Pineapple",
				"Corn"
			}
		},
		Donut = {
			{
				"Corn",
				"Blueberry",
				"Strawberry"
			},
			{
				"Strawberry",
				"Tomato",
				"Apple"
			}
		},
		Pizza = {
			"Corn",
			"Tomato",
			"Pepper"
		},
		Cake = {
			"Watermelon",
			"Corn"
		}
	},
	Variants = {
		"Normal",
		"Gold",
		"Rainbow"
	},
	Teleports = {
		"Seeds Shop",
		"Sell Shop",
		"Gear Shop",
		"Cosmetics Shop",
		"Eggs Shop",
		"Event Area"
	},
	Recipes = {
		MiniWorkbench = {
			"Aloe Vera",
			"Amber Spine",
			"Bee Balm",
			"Crafters Seed Pack",
			"Dandelion",
			"Grand Volcania",
			"Guanabana",
			"Honeysuckle",
			"Horsetail",
			"Lingonberry",
			"Lumira",
			"Manuka Flower",
			"Nectar Thorn",
			"Peace Lily",
			"Suncoil",
			"Twisted Tangle",
			"Veinpetal"
		},
		LargeWorkbench = {
			"Anti Bee Egg",
			"Berry Blusher Sprinkler",
			"Flower Froster Sprinkler",
			"Honey Crafters Crate",
			"Lightning Rod",
			"Mutation Spray Chilled",
			"Mutation Spray Choc",
			"Mutation Spray Pollinated",
			"Mutation Spray Shocked",
			"Pack Bee",
			"Pet Pouch",
			"Reclaimer",
			"Small Treat",
			"Small Toy",
			"Spice Spritzer Sprinkler",
			"Stalk Sprout Sprinkler",
			"Sweet Soaker Sprinkler",
			"Tanning Mirror",
			"Tropical Mist Sprinkler"
		},
    LargeWorkbench = {
			"Anti Bee Egg",
			"Berry Blusher Sprinkler",
			"Flower Froster Sprinkler",
			"Honey Crafters Crate",
			"Lightning Rod",
			"Mutation Spray Chilled",
			"Mutation Spray Choc",
			"Mutation Spray Pollinated",
			"Mutation Spray Shocked",
			"Pack Bee",
			"Pet Pouch",
			"Reclaimer",
			"Small Treat",
			"Small Toy",
			"Spice Spritzer Sprinkler",
			"Stalk Sprout Sprinkler",
			"Sweet Soaker Sprinkler",
			"Tanning Mirror",
			"Tropical Mist Sprinkler"
		},
    EventWorkbench = {
			"Skyroot Chest",
      "Sprout Egg",
      "Willowberry",
      "Green Bean Memories",
      "Bean Pool Table",
      "Bean Sprout Float Light",
      "Pet Shard GiantBean",
		},
	},
	ServerEvents = {
      ["Rain"] = "RainEvent",
      ["Thunderstorm"] = "Thunderstorm",
      ["Frost"] = "Frost",
      ["Sheckle Rain"] = "SheckleRain",
      ["Meteor Shower"] = "MeteorShower",
      ["Chocolate Rain"] = "ChocolateRain",
      ["Jandel Storm"] = "JandelStorm",
      ["D J Jhai"] = "DJJhai",
      ["Tornado"] = "Tornado",
      ["Monster Mash"] = "MonsterMash",
      ["Jandel Lazer"] = "JandelLazer",
      ["Bee Nado"] = "BeeNado",
      ["Bee Storm"] = "BeeStorm",
      ["Blackhole"] = "Blackhole",
      ["Bee Event"] = "BeeEvent",
      ["Rainbow"] = "Rainbow",
      ["Jandel Float"] = "JandelFloat",
      ["Windy"] = "Windy",
      ["Sun God"] = "SunGod",
      ["Volcano"] = "Volcano",
      ["Meteor Strike"] = "MeteorStrike",
      ["Heatwave"] = "Heatwave",
      ["Alien Invasion"] = "AlienInvasion",
      ["Space Travel"] = "SpaceTravel",
      ["Under The Sea"] = "UnderTheSea",
      ["Gale"] = "Gale",
      ["Summer Event"] = "SummerEvent",
      ["Solar Flare"] = "SolarFlare",
      ["Drought"] = "Drought",
      ["Tropical Rain"] = "TropicalRain",
      ["Chicken Rain"] = "ChickenRain",
      ["Aurora Borealis"] = "AuroraBorealis",
      ["Sandstorm"] = "Sandstorm",
      ["Shooting Stars"] = "ShootingStars",
      ["D J Sandstorm"] = "DJSandstorm",
      ["Obby"] = "Obby",
      ["Pool Party"] = "PoolParty",
      ["Air Head"] = "AirHead",
      ["Crystal Beams"] = "CrystalBeams",
      ["Cooking"] = "Cooking",
      ["Jandel Zombie"] = "JandelZombie",
      ["Radioactive Carrot"] = "RadioactiveCarrot",
      ["Armageddon"] = "Armageddon",
      ["Enlightenment"] = "Enlightenment",
      ["Solar Eclipse"] = "SolarEclipse",
      ["Acid Rain"] = "AcidRain",
      ["T K_ Lightning Storm"] = "TK_LightningStorm",
      ["T K_ Money Rain"] = "TK_MoneyRain",
      ["T K_ Route Runner"] = "TK_RouteRunner",
      ["T K_ Post Dunk"] = "TK_PostDunk",
      ["Jandel Katana"] = "JandelKatana",
      ["Stoplight"] = "Stoplight",
      ["Enchantment"] = "Enchantment",
      ["Junkbot Raid"] = "JunkbotRaid",
      ["Oil"] = "Oil",
      ["Boil"] = "Boil",
      ["Flamingo Lazer"] = "FlamingoLazer",
      ["Flamingo Float"] = "FlamingoFloat",
      ["Beanaura"] = "Beanaura",
      ["Brainrot  Portal"] = "Brainrot Portal",
      ["Brainrot  Stampede"] = "Brainrot Stampede",
      ["Dissonant"] = "Dissonant",
      ["Boombox Party"] = "BoomboxParty"
  },
	TeleportLocations = {
		["Garden"] = CFrame.new(0, 0, 0),
		["Seeds Shop"] = CFrame.new(62, 3, -27),
		["Sell Shop"] = CFrame.new(-259, 3, -9),
		["Gear Shop"] = CFrame.new(-285, 3, -33),
		["Cosmetics Shop"] = CFrame.new(-285, 3, -15),
		["Eggs Shop"] = CFrame.new(-284, 3, -2),
		["Event Area"] = CFrame.new(-101, 4, -7)
	},
	Temp = {
		["Berry"] = {
			"Blueberry",
			"Cranberry",
			"Grape",
			"Raspberry",
			"Strawberry",
			"Celestiberry",
			"White Mullberry",
			"Lingonberry",
			"Elder Strawberry"
		},
		["Root"] = {
			"Carrot",
			"Mutant Carrot",
			"Chocolate Carrot",
			"Wild Carrot",
			"Taro Flower",
			"Potato",
			"Mandrake",
			"Rhubarb",
			"Onion",
			"Tall Asparagus",
			"Horsetail"
		},
		["Candy"] = {
			"Blue Lollipop",
			"Candy Blossom",
			"Candy Sunflower",
			"Chocolate Carrot",
			"Easter Egg",
			"Red Lollipop",
			"Sugarglaze"
		},
		["Flower"] = {
			"Candy Blossom",
			"Candy Sunflower",
			"Cherry Blossom",
			"Crocus",
			"Daffodil",
			"Lotus",
			"Orange Tulip",
			"Pink Tulip",
			"Nightshade",
			"Moonflower",
			"Moon Blossom",
			"Rose",
			"Foxglove",
			"Lilac",
			"Pink Lily",
			"Purple Dahlia",
			"Sunflower",
			"Lavender",
			"Honeysuckle",
			"Manuka Flower",
			"Ember Lily",
			"Noble Flower",
			"Bee Balm",
			"Succulent",
			"Parasol Flower",
			"Rosy Delight",
			"Lily of the Valley",
			"Burning Bud",
			"Rafflesia",
			"Stonebite",
			"Liberty Lily",
			"Firework Flower",
			"Grand Volcania",
			"Serenity",
			"Monoblooma",
			"Soft Sunshine",
			"Hinomai",
			"Taro Flower",
			"Zenflare",
			"Soft Sunshine",
			"Dezen",
			"Artichoke",
			"Veinpetal",
			"Cyclamen",
			"Flare Daisy"
		},
		["Fruit"] = {
			"Apple",
			"Avocado",
			"Banana",
			"Blueberry",
			"Coconut",
			"Cranberry",
			"Dragon Fruit",
			"Durian",
			"Grape",
			"Lemon",
			"Lime",
			"Mango",
			"Papaya",
			"Passionfruit",
			"Peach",
			"Pear",
			"Pineapple",
			"Raspberry",
			"Strawberry",
			"Watermelon",
			"Starfruit",
			"Blood Banana",
			"Moon Melon",
			"Celestiberry",
			"Moon Mango",
			"Nectarine",
			"Hive Fruit",
			"Green Apple",
			"Sugar Apple",
			"Traveler\'s Fruit",
			"Loquat",
			"Kiwi",
			"White Mullberry",
			"Lingonberry",
			"Maple Apple",
			"Spiked Mango",
			"Crown Melon",
			"Grand Tomato",
			"Pricklefruit",
			"Mangosteen",
			"Canary Melon"
		},
		["Leafy"] = {
			"Apple",
			"Blueberry",
			"Cranberry",
			"Eggplant",
			"Grape",
			"Mango",
			"Peach",
			"Pineapple",
			"Pumpkin",
			"Raspberry",
			"Strawberry",
			"Tomato",
			"Watermelon",
			"Cantaloupe",
			"Cacao",
			"Beanstalk",
			"Mint",
			"Moonflower",
			"Starfruit",
			"Moonglow",
			"Moon Blossom",
			"Blood Banana",
			"Celestiberry",
			"Moon Mango",
			"Rose",
			"Foxglove",
			"Lilac",
			"Pink Lily",
			"Purple Dahlia",
			"Sunflower",
			"Nectarine",
			"Hive Fruit",
			"Lumira",
			"Honeysuckle",
			"Noble Flower",
			"Bee Balm",
			"Green Apple",
			"Sugar Apple",
			"Parasol Flower",
			"Elephant Ears",
			"Traveler\'s Fruit",
			"Rosy Delight",
			"Cauliflower",
			"Aloe Vera",
			"Lily of the Valley",
			"Pitcher Plant",
			"Rafflesia",
			"Firefly Fern",
			"Giant Pinecone",
			"Serenity",
			"Soft Sunshine",
			"Dragon Sapling",
			"Maple Apple",
			"Spiked Mango",
			"Sakura Bush",
			"Grand Tomato",
			"Artichoke",
			"Twisted Tangle",
			"Log Pumpkin",
			"Mandrake",
			"Cyclamen",
			"Mangosteen",
			"Princess Thorn",
			"Romanesco"
		},
		["Sour"] = {
			"Cranberry",
			"Lemon",
			"Lime",
			"Passionfruit",
			"Starfruit",
			"Mangosteen"
		},
		["Sweet"] = {
			"Banana",
			"Blue Lollipop",
			"Blueberry",
			"Candy Blossom",
			"Candy Sunflower",
			"Chocolate Carrot",
			"Easter Egg",
			"Grape",
			"Mango",
			"Peach",
			"Pear",
			"Pineapple",
			"Raspberry",
			"Red Lollipop",
			"Strawberry",
			"Watermelon",
			"Starfruit",
			"Nectar Thorn",
			"Sugar Apple",
			"Moon Melon",
			"Spiked Mango",
			"Sugarglaze",
			"Crown Melon",
			"Sugarglaze",
			"Mangosteen",
			"Canary Melon",
			"Romanesco"
		},
		["Tropical"] = {
			"Banana",
			"Coconut",
			"Dragon Fruit",
			"Durian",
			"Mango",
			"Papaya",
			"Passionfruit",
			"Pineapple",
			"Watermelon",
			"Parasol Flower",
			"Cocovine",
			"Starfruit"
		},
		["Vegetable"] = {
			"Carrot",
			"Wild Carrot",
			"Chocolate Carrot",
			"Corn",
			"Violet Corn",
			"Eggplant",
			"Pepper",
			"Pumpkin",
			"Purple Cabbage",
			"Tomato",
			"Beanstalk",
			"Mint",
			"Dragon Pepper",
			"Cauliflower",
			"Bell Pepper",
			"Taro Flower",
			"Artichoke",
			"Onion",
			"Jalapeno",
			"Tall Asparagus",
			"Grand Tomato",
			"Log Pumpkin",
			"Badlands Pepper",
			"Rhubarb",
			"King Cabbage",
			"Bitter Melon",
			"Mandrake",
			"Mutant Carrot",
			"Romanesco"
		},
		["Woody"] = {
			"Apple",
			"Avocado",
			"Cacao",
			"Coconut",
			"Durian",
			"Mango",
			"Papaya",
			"Peach",
			"Pear",
			"Moon Blossom",
			"Moon Mango",
			"Nectarine",
			"Hive Fruit",
			"Cocovine",
			"Traveler\'s Fruit",
			"Kiwi",
			"Feijoa",
			"Giant Pinecone",
			"Dragon Sapling",
			"Maple Apple",
			"Spiked Mango",
			"Sakura Bush",
			"Rhubarb",
			"Duskpuff",
			"Mangosteen",
			"Gleamroot",
			"Amberheart"
		},
		["Prickly"] = {
			"Cactus",
			"Dragon Fruit",
			"Durian",
			"Pineapple",
			"Venus Fly Trap",
			"Celestiberry",
			"Nectar Thorn",
			"Prickly Pear",
			"Aloe Vera",
			"Horned Dinoshroom",
			"Spiked Mango",
			"Twisted Tangle",
			"Pricklefruit",
			"Princess Thorn"
		},
		["Toxic"] = {
			"Foxglove",
			"Nightshade",
			"Rafflesia",
			"Pithcer Plant",
			"Horned Dinoshroom",
			"Sinisterdrip",
			"Cursed Fruit",
			"Amber Spine"
		},
		["Fungus"] = {
			"Mega Mushroom",
			"Mushroom",
			"Glowshroom",
			"Nectarshade",
			"Horned Dinoshroom",
			"Sinisterdrip",
			"Duskpuff"
		},
		["Night"] = {
			"Blood Banana",
			"Moon Melon",
			"Nightshade",
			"Glowshroom",
			"Mint",
			"Moonflower",
			"Starfruit",
			"Moonglow",
			"Moon Blossom",
			"Moon Mango",
			"Celestiberry",
			"Aura Flora",
			"Gleamroot"
		},
		["Spicy"] = {
			"Cursed Fruit",
			"Ember Lily",
			"Pepper",
			"Dragon Pepper",
			"Cacao",
			"Horned Dinoshroom",
			"Grand Volcania",
			"Jalapeno",
			"Badlands Pepper"
		},
		["Stalky"] = {
			"Beanstalk",
			"Burning Bud",
			"Bamboo",
			"Dandelion",
			"Mushroom",
			"Bendboo",
			"Lotus",
			"Elephant Ears",
			"Lily of the Valley",
			"Pitcher Plant",
			"Stonebite",
			"Firefly Fern",
			"Horned Dinoshroom",
			"Grand Volcania",
			"Soft Sunshine",
			"Hinomai",
			"Sinisterdrip",
			"Lucky Bamboo",
			"Sugarglaze",
			"Tall Asparagus",
			"Veinpetal",
			"Pricklefruit",
			"Spring Onion",
			"Mutant Carrot",
			"Poseidon Plant"
		},
		["Summer"] = {
			"Carrot",
			"Strawberry",
			"Blueberry",
			"Tomato",
			"Watermelon",
			"Rafflesia",
			"Cauliflower",
			"Green Apple",
			"Avocado",
			"Banana",
			"Pineapple",
			"Kiwi",
			"Bell Pepper",
			"Prickly Pear",
			"Loquat",
			"Feijoa",
			"Pitcher Plant",
			"Sugar Apple",
			"Wild Carrot",
			"Pear",
			"Cantaloupe",
			"Parasol Flower",
			"Rosy Delight",
			"Elephant Ears",
			"Delphinium",
			"Lily of the Valley",
			"Traveler\'s Fruit",
			"Peace Lily",
			"Aloe Vera",
			"Guanabana",
			"Butternut Squash"
		},
		["Prehistoric"] = {
			"Stonebite",
			"Paradise Petal",
			"Horned Dinoshroom",
			"Boneboo",
			"Firefly Fern",
			"Fossilight",
			"Bone Blossom",
			"Horsetail",
			"Lingonberry",
			"Amber Spine",
			"Grand Volcania"
		},
		["Zen"] = {
			"Monoblooma",
			"Serenity",
			"Taro Flower",
			"Zen Rocks",
			"Hinomai",
			"Maple Apple",
			"Zenflare",
			"Soft Sunshine",
			"Spiked Mango",
			"Sakura Bush",
			"Enkaku",
			"Dezen",
			"Lucky Bamboo",
			"Tranquil Bloom"
		}
	}
}
