return {
    ["AllItems"] = {
        "Avocado Seed",
        "Bald Eagle",
        "Banana Seed",
        "Bee Crate",
        "Bee Egg",
        "Bell Pepper Seed",
        "Cauliflower Seed",
        "Classic Gnome Crate",
        "Common Gnome Crate",
        "Farmers Gnome Crate",
        "Feijoa Seed",
        "Firework",
        "Firework Flower",
        "Flower Seed Pack",
        "Green Apple Seed",
        "Honey Crafters Crate",
        "Honey Sprinkler",
        "Iconic Gnome Crate",
        "July 4th Crate",
        "Kiwi Seed",
        "Liberty Lily",
        "Loquat Seed",
        "Mutation Spray Cloudtouched",
        "Mutation Spray Verdant",
        "Mutation Spray Wet",
        "Mutation Spray Windstruck",
        "Night Staff",
        "Pineapple Seed",
        "Pitcher Plant",
        "Prickly Pear Seed",
        "Rafflesia Seed",
        "Star Caller",
        "Tropical Mist Sprinkler",
        "Berry Blusher Sprinkler",
        "Spice Spritzer Sprinkler",
        "Sweet Soaker Sprinkler",
        "Flower Froster Sprinkler",
        "Stalk Sprout Sprinkler",
    }
}
