return {

    -- 4th July (American Traveling Merchant)
    ["American Traveling Merchant"] = {

        ["Liberty Lily"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 519,
            ItemType      = "Seed",
            LayoutOrder   = 10,
            Price         = 650000,
            PurchaseID    = 3322972631,
            SeedName      = "Liberty Lily",
            SeedRarity    = "Rare",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Firework Flower"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 249,
            ItemType      = "Seed",
            LayoutOrder   = 15,
            Price         = 150000,
            PurchaseID    = 3322974839,
            SeedName      = "Firework Flower",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Firework"] = {
            Description   = "Launches fireworks!",
            DisplayInShop = true,
            FallbackPrice = 39,
            ItemType      = "Gear",
            LayoutOrder   = 20,
            Price         = 74000,
            PurchaseID    = 3322978636,
            SeedName      = "Firework",
            SeedRarity    = "Rare",
            ShowOdds      = true,
            Stack         = 5,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Bald Eagle"] = {
            Description   = "Wings of Freedom: Occasionally flaps its wings of freedom and advances hatch time for all eggs in your garden!",
            DisplayInShop = true,
            FallbackPrice = 899,
            ItemType      = "Pet",
            LayoutOrder   = 30,
            Price         = 7400000,
            PurchaseID    = 3322970897,
            SeedName      = "Bald Eagle",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["July 4th Crate"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 179,
            ItemType      = "Crate",
            LayoutOrder   = 40,
            Price         = 7400000,
            PurchaseID    = 3322970196,
            SeedName      = "July 4th Crate",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },
    },

    -- Gnome (Gnome Traveling Merchant)
    ["Gnome Traveling Merchant"] = {

        ["Common Gnome Crate"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 149,
            ItemType      = "Crate",
            LayoutOrder   = 10,
            Price         = 55500000,
            PurchaseID    = 3290108955,
            SeedName      = "Common Gnome Crate",
            SeedRarity    = "Common",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Farmers Gnome Crate"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 179,
            ItemType      = "Crate",
            LayoutOrder   = 20,
            Price         = 88500000,
            PurchaseID    = 3290109302,
            SeedName      = "Farmers Gnome Crate",
            SeedRarity    = "Rare",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Classic Gnome Crate"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 199,
            ItemType      = "Crate",
            LayoutOrder   = 30,
            Price         = 113000000,
            PurchaseID    = 3290109380,
            SeedName      = "Classic Gnome Crate",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },

        ["Iconic Gnome Crate"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 199,
            ItemType      = "Crate",
            LayoutOrder   = 40,
            Price         = 155000000,
            PurchaseID    = 3317148476,
            SeedName      = "Iconic Gnome Crate",
            SeedRarity    = "Mythical",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 4,
        },
    },

    -- Honey (Honey Traveling Merchant)
    ["Honey Traveling Merchant"] = {

        ["Flower Seed Pack"] = {
            Description         = "",
            DisplayInShop       = true,
            FallbackPrice       = 199,
            ItemType            = "Seed Pack",
            LayoutOrder         = 1,
            Price               = 10,
            PurchaseID          = 3295395160,
            SeedName            = "Flower Seed Pack",
            SeedRarity          = "Rare",
            ShowOdds            = true,
            SpecialCurrencyType = "Honey",
            Stack               = 1,
            StockAmount         = {} --[[ TABLE ]],
            StockChance         = 1,
        },

        ["Honey Sprinkler"] = {
            Description         = "Covers nearby plants in honey! Lasts 1 minute",
            DisplayInShop       = true,
            FallbackPrice       = 199,
            ItemType            = "Gear",
            LayoutOrder         = 25,
            Price               = 30,
            PurchaseID          = 3295397583,
            SeedName            = "Honey Sprinkler",
            SeedRarity          = "Divine",
            SpecialCurrencyType = "Honey",
            Stack               = 1,
            StockAmount         = {} --[[ TABLE ]],
            StockChance         = 6,
        },

        ["Bee Egg"] = {
            Description         = "",
            DisplayInShop       = true,
            FallbackPrice       = 129,
            ItemType            = "Egg",
            LayoutOrder         = 30,
            Price               = 18,
            PurchaseID          = 3295398638,
            SeedName            = "Bee Egg",
            SeedRarity          = "Mythical",
            ShowOdds            = true,
            SpecialCurrencyType = "Honey",
            Stack               = 1,
            StockAmount         = {} --[[ TABLE ]],
            StockChance         = 1,
        },

        ["Bee Crate"] = {
            Description         = "",
            DisplayInShop       = true,
            FallbackPrice       = 179,
            ItemType            = "Crate",
            LayoutOrder         = 40,
            Price               = 12,
            PurchaseID          = 3295396781,
            SeedName            = "Bee Crate",
            SeedRarity          = "Legendary",
            ShowOdds            = true,
            SpecialCurrencyType = "Honey",
            Stack               = 1,
            StockAmount         = {} --[[ TABLE ]],
            StockChance         = 4,
        },

        ["Honey Crafters Crate"] = {
            Description         = "",
            DisplayInShop       = true,
            FallbackPrice       = 179,
            ItemType            = "Crate",
            LayoutOrder         = 50,
            Price               = 15,
            PurchaseID          = 3306484248,
            SeedName            = "Honey Crafters Crate",
            SeedRarity          = "Legendary",
            ShowOdds            = true,
            SpecialCurrencyType = "Honey",
            Stack               = 1,
            StockAmount         = {} --[[ TABLE ]],
            StockChance         = 4,
        },
    },

    -- Sky (Sky Traveling Merchant)
    ["Sky Traveling Merchant"] = {

        ["Night Staff"] = {
            Description   = "Grants extra moonlit mutations per night cycle",
            DisplayInShop = true,
            FallbackPrice = 199,
            ItemType      = "Gear",
            LayoutOrder   = 1,
            Price         = 12000000,
            PurchaseID    = 3317153937,
            SeedName      = "Night Staff",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Star Caller"] = {
            Description   = "Attracts shooting stars",
            DisplayInShop = true,
            FallbackPrice = 219,
            ItemType      = "Gear",
            LayoutOrder   = 10,
            Price         = 15000000,
            PurchaseID    = 3286452366,
            SeedName      = "Star Caller",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },

        ["Mutation Spray Cloudtouched"] = {
            Description   = "Fruits become blessed by clouds!",
            DisplayInShop = true,
            FallbackPrice = 199,
            ItemType      = "Gear",
            LayoutOrder   = 20,
            Price         = 50000000,
            PurchaseID    = 3317773711,
            SeedName      = "Mutation Spray Cloudtouched",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 3,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },
    },

    -- Spray (Spray Traveling Merchant)
    ["Spray Traveling Merchant"] = {

        ["Mutation Spray Wet"] = {
            Description   = "Wets a fruit!",
            DisplayInShop = true,
            FallbackPrice = 179,
            ItemType      = "Gear",
            LayoutOrder   = 10,
            Price         = 50000000,
            PurchaseID    = 3337928013,
            SeedName      = "Mutation Spray Wet",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Mutation Spray Windstruck"] = {
            Description   = "Fruits become Windy!",
            DisplayInShop = true,
            FallbackPrice = 189,
            ItemType      = "Gear",
            LayoutOrder   = 20,
            Price         = 50000000,
            PurchaseID    = 3337928540,
            SeedName      = "Mutation Spray Windstruck",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Mutation Spray Verdant"] = {
            Description   = "Fruits become Verdant!",
            DisplayInShop = true,
            FallbackPrice = 179,
            ItemType      = "Gear",
            LayoutOrder   = 30,
            Price         = 50000000,
            PurchaseID    = 3337929108,
            SeedName      = "Mutation Spray Verdant",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },
    },

    -- Summer (Summer Traveling Merchant)
    ["Summer Traveling Merchant"] = {

        ["Cauliflower"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 135,
            ItemType      = "Seed",
            LayoutOrder   = 10,
            Price         = 1300,
            PurchaseID    = 3312007044,
            SeedName      = "Cauliflower Seed",
            SeedRarity    = "Rare",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Rafflesia"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 215,
            ItemType      = "Seed",
            LayoutOrder   = 20,
            Price         = 3200,
            PurchaseID    = 3317729900,
            SeedName      = "Rafflesia Seed",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 1,
        },

        ["Green Apple"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 399,
            ItemType      = "Seed",
            LayoutOrder   = 30,
            Price         = 3500,
            PurchaseID    = 3312008833,
            SeedName      = "Green Apple Seed",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },

        ["Avocado"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 419,
            ItemType      = "Seed",
            LayoutOrder   = 40,
            Price         = 5000,
            PurchaseID    = 3312011056,
            SeedName      = "Avocado Seed",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },

        ["Banana"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 459,
            ItemType      = "Seed",
            LayoutOrder   = 50,
            Price         = 7000,
            PurchaseID    = 3269001250,
            SeedName      = "Banana Seed",
            SeedRarity    = "Legendary",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 2,
        },

        ["Pineapple"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 475,
            ItemType      = "Seed",
            LayoutOrder   = 60,
            Price         = 7500,
            PurchaseID    = 3312005774,
            SeedName      = "Pineapple Seed",
            SeedRarity    = "Mythical",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 3,
        },

        ["Kiwi"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 529,
            ItemType      = "Seed",
            LayoutOrder   = 70,
            Price         = 10000,
            PurchaseID    = 3312011732,
            SeedName      = "Kiwi Seed",
            SeedRarity    = "Mythical",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 4,
        },

        ["Bell Pepper"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 589,
            ItemType      = "Seed",
            LayoutOrder   = 80,
            Price         = 55000,
            PurchaseID    = 3312012483,
            SeedName      = "Bell Pepper Seed",
            SeedRarity    = "Mythical",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 4,
        },

        ["Prickly Pear"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 599,
            ItemType      = "Seed",
            LayoutOrder   = 90,
            Price         = 555000,
            PurchaseID    = 3312013208,
            SeedName      = "Prickly Pear Seed",
            SeedRarity    = "Mythical",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 9,
        },

        ["Loquat"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 629,
            ItemType      = "Seed",
            LayoutOrder   = 100,
            Price         = 900000,
            PurchaseID    = 3312014286,
            SeedName      = "Loquat Seed",
            SeedRarity    = "Divine",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 10,
        },

        ["Feijoa"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 679,
            ItemType      = "Seed",
            LayoutOrder   = 110,
            Price         = 2750000,
            PurchaseID    = 3312013874,
            SeedName      = "Feijoa Seed",
            SeedRarity    = "Divine",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 11,
        },

        ["Pitcher Plant"] = {
            Description   = "",
            DisplayInShop = true,
            FallbackPrice = 715,
            ItemType      = "Seed",
            LayoutOrder   = 120,
            Price         = 7500000,
            PurchaseID    = 3317730202,
            SeedName      = "Pitcher Plant",
            SeedRarity    = "Divine",
            ShowOdds      = true,
            Stack         = 1,
            StockAmount   = {} --[[ TABLE ]],
            StockChance   = 12,
        },
    },

    -- Alphabetical list of all item names
    ["AllItems"] = {
        "Avocado Seed",
        "Bald Eagle",
        "Banana Seed",
        "Bee Crate",
        "Bee Egg",
        "Bell Pepper Seed",
        "Cauliflower Seed",
        "Classic Gnome Crate",
        "Common Gnome Crate",
        "Farmers Gnome Crate",
        "Feijoa Seed",
        "Firework",
        "Firework Flower",
        "Flower Seed Pack",
        "Green Apple Seed",
        "Honey Crafters Crate",
        "Honey Sprinkler",
        "Iconic Gnome Crate",
        "July 4th Crate",
        "Kiwi Seed",
        "Liberty Lily",
        "Loquat Seed",
        "Mutation Spray Cloudtouched",
        "Mutation Spray Verdant",
        "Mutation Spray Wet",
        "Mutation Spray Windstruck",
        "Night Staff",
        "Pineapple Seed",
        "Pitcher Plant",
        "Prickly Pear Seed",
        "Rafflesia Seed",
        "Star Caller",
    },
}
