return {
    ["AllItems"] = {
        "Avocado",
        "Bald Eagle",
        "Banana",
        "Bee Crate",
        "Bee Egg",
        "Bell Pepper",
        "Berry Blusher Sprinkler",
        "Bonfire",
        "Cauliflower",
        "Chipmunk",
        "Classic Gnome Crate",
        "Common Gnome Crate",
        "Common Summer Egg",
        "Fall Crate",
        "Fall Egg",
        "Fall Fountain",
        "Fall Seed Pack",
        "Farmers Gnome Crate",
        "Feijoa",
        "Firework",
        "Firework Flower",
        "Flower Froster Sprinkler",
        "Flower Seed Pack",
        "Gnome",
        "Green Apple",
        "Harvest Basket",
        "Honey Crafters Crate",
        "Honey Sprinkler",
        "Iconic Gnome Crate",
        "July 4th Crate",
        "Kiwi",
        "Kniphofia",
        "Liberty Lily",
        "Loquat",
        "Maple Crate",
        "Maple Resin",
        "Mutation Spray Cloudtouched",
        "Mutation Spray Verdant",
        "Mutation Spray Wet",
        "Mutation Spray Windstruck",
        "Night Staff",
        "Paradise Egg",
        "Pineapple",
        "Pitcher Plant",
        "Prickly Pear",
        "Rafflesia",
        "Rake",
        "Rare Summer Egg",
        "Red Panda",
        "Space Squirrel",
        "Spice Spritzer Sprinkler",
        "Stalk Sprout Sprinkler",
        "Star Caller",
        "Super Leaf Blower",
        "Sweet Soaker Sprinkler",
        "Tropical Mist Sprinkler"
    }
}
