local v5 = Instance.new("Folder")
local v7 = {
	["Dog"] = {
		["Description"] = "Digging Buddy: Occasionally digs up a random seed",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Dog"),
		["DefaultHunger"] = 1000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://135018170520317",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 55000,
		["Rarity"] = "Common",
		["Passives"] = {
			"Digging Buddy"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Golden Lab"] = {
		["Description"] = "Digging Friend: Occasionally digs up a random seed at a higher chance",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Dog"),
		["Variant"] = "Golden Lab",
		["DefaultHunger"] = 1200,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://99376934607716",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 55000,
		["Rarity"] = "Common",
		["Passives"] = {
			"Digging Friend"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Bunny"] = {
		["Description"] = "Carrot Chomper: Runs to carrots, eats them, and grants bonus sheckles (more than normal value)",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bunny"),
		["DefaultHunger"] = 1100,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://85830855120751",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 55000,
		["Rarity"] = "Common",
		["Passives"] = {
			"Carrot Chomper"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Black Bunny"] = {
		["Description"] = "Carrot Devourer: Runs to carrots, eats them, and grants bonus sheckles (more than normal value)",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bunny"),
		["Variant"] = "Black Bunny",
		["DefaultHunger"] = 1300,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://86614624778104",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 165000,
		["Rarity"] = "Uncommon",
		["Passives"] = {
			"Carrot Chomper"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Cat"] = {
		["Description"] = "Cat Nap: Cat naps in a random spot in your farm, emitting an aura that boosts nearby fruit size",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Cat"),
		["DefaultHunger"] = 1400,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://136444015144013",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 12,
		["SellPrice"] = 165000,
		["Rarity"] = "Uncommon",
		["Passives"] = {
			"Cat Nap"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Deer"] = {
		["Description"] = "Forester: When harvesting berry plants, there is a chance the fruit will remain",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Deer"),
		["DefaultHunger"] = 2500,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.009,
		["Icon"] = "rbxassetid://91926785467809",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 12,
		["SellPrice"] = 165000,
		["Rarity"] = "Uncommon",
		["Passives"] = {
			"Forester"
		},
		["YHeightScaler"] = 0.65,
		["States"] = {}
	},
	["Chicken"] = {
		["Description"] = "Eggcelerator: Decreases the time needed to hatch other eggs",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Chicken"),
		["DefaultHunger"] = 3400,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://108080824427369",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 165000,
		["Rarity"] = "Uncommon",
		["Passives"] = {
			"Eggcelerator"
		},
		["YHeightScaler"] = 0.15,
		["States"] = {}
	},
	["Orange Tabby"] = {
		["Description"] = "Orange Tabby: Orange Tabby naps in a random spot in your farm, emitting an aura that boosts nearby fruit size",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Cat"),
		["Variant"] = "Orange Tabby",
		["DefaultHunger"] = 1500,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://103360220936666",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 12,
		["SellPrice"] = 660000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Lazy Nap"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Spotted Deer"] = {
		["Description"] = "Forester: When harvesting berry plants, there is a chance the fruit will remain",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Spotted Deer"),
		["DefaultHunger"] = 2500,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.009,
		["Icon"] = "rbxassetid://126439207915258",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 12,
		["SellPrice"] = 660000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Spotted Forester"
		},
		["YHeightScaler"] = 0.65,
		["States"] = {}
	},
	["Rooster"] = {
		["Description"] = "Eggcelerator: Decreases the time needed to hatch other eggs",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rooster"),
		["DefaultHunger"] = 4000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://137107493326109",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 650000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Better Eggcelerator"
		},
		["YHeightScaler"] = 0.15,
		["States"] = {}
	},
	["Monkey"] = {
		["Description"] = "Cheeky Refund: 3% chance to get your fruit back when you sell it",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Monkey"),
		["DefaultHunger"] = 7400,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://113881196210664",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 660000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Cheeky Refund"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Pig"] = {
		["Description"] = "Fertilizer Frenzy: Occasionally releases a fertilizing AOE boosting plant size and mutation chance",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Pig"),
		["DefaultHunger"] = 5000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.008,
		["Icon"] = "rbxassetid://134476443266448",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 650000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Fertilizer Frenzy"
		},
		["YHeightScaler"] = 0.6,
		["States"] = {}
	},
	["Silver Monkey"] = {
		["Description"] = "Cheeky Refund: 3% chance to get your fruit back when you sell it",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Monkey"),
		["Variant"] = "Silver Monkey",
		["DefaultHunger"] = 8000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://136985272620600",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Premium Cheeky Refund"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Turtle"] = {
		["Description"] = "Turtle Tinkerer: Slowing aura that makes sprinklers last longer",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Turtle"),
		["DefaultHunger"] = 10000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.004,
		["Icon"] = "rbxassetid://92906330087175",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 5,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Turtle Tinkerer"
		},
		["YHeightScaler"] = -0.32,
		["States"] = {}
	},
	["Cow"] = {
		["Description"] = "Milk of the Land: Fertilizing aura that boosts nearby plant growth speed ",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Cow"),
		["DefaultHunger"] = 9500,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://118832676475537",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["YHeightScaler"] = 0.5,
		["Passives"] = {
			"Milk of the Land"
		},
		["States"] = {}
	},
	["Sea Otter"] = {
		["Description"] = "Water Spray: Water\'s plants randomly like a watering can",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Sea Otter"),
		["DefaultHunger"] = 30000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://94422445572440",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Water Spray"
		},
		["YHeightScaler"] = -0.25,
	},
	["Polar Bear"] = {
		["Description"] = "Polar Express: Occasionally sets a random nearby fruit cold, turning it into Chilled with a small chance for Frozen",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Polar Bear"),
		["DefaultHunger"] = 20000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://72209118254193",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Polar Express"
		},
		["YHeightScaler"] = 0.35,
	},
	["Caterpillar"] = {
		["Description"] = "Leaf Lover Passive: Boost nearby Leafy plants growth rate",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Caterpillar"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.0065,
		["Icon"] = "rbxassetid://119651461526366",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 6,
		["SellPrice"] = 50000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Leaf Lover"
		},
		["YHeightScaler"] = -0.55,
	},
	["Snail"] = {
		["Description"] = "Slow and Steady: Increased lucky harvest chance",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Snail"),
		["DefaultHunger"] = 12000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, 3.141592653589793),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://80970021440625",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 3,
		["SellPrice"] = 50000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Slow and Steady"
		},
		["YHeightScaler"] = 0,
		["States"] = {}
	},
	["Giant Ant"] = {
		["Description"] = "For the Blue Colony: Small chance to duplicate harvested plant & Prehistoric Harvester: Increased chance to duplicate harvested candy type plant",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Giant Ant"),
		["DefaultHunger"] = 18000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, 3.141592653589793),
		["ModelScalePerLevel"] = 0.003,
		["Icon"] = "rbxassetid://71413253805996",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 5,
		["SellPrice"] = 60000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"For the Blue Colony",
			"Candy Harvester"
		},
		["YHeightScaler"] = 0.4,
	},
	["Praying Mantis"] = {
		["Description"] = "Zen Zone: Prays, then gives plants in AOE Buff that increases the chance of gold fruit from plants",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Praying Mantis"),
		["DefaultHunger"] = 55000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, 3.141592653589793),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://121485029406440",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 60000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Zen Zone"
		},
		["YHeightScaler"] = 0.1,
	},
	["Dragonfly"] = {
		["Description"] = "Transmutation: Every now and then turns a fruit to gold",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Dragonfly"),
		["DefaultHunger"] = 100000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ModelScalePerLevel"] = 0.008,
		["Icon"] = "rbxassetid://118484611393651",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 70000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Transmutation"
		},
		["YHeightScaler"] = 0.4,
	},
	["Panda"] = {
		["Description"] = "Bamboozle: Waddles to bamboo, eats it, and grants bonus sheckles (more than normal value)",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Panda"),
		["DefaultHunger"] = 20000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://107090327345246",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Bamboozle"
		},
		["YHeightScaler"] = 0.35,
	},
	["Hedgehog"] = {
		["Description"] = "Prickly Lover: Makes nearby prickly fruit grow bigger",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Hedgehog"),
		["DefaultHunger"] = 30000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://83544966481425",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 7,
		["SellPrice"] = 1000000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Prickly Lover"
		},
		["YHeightScaler"] = 0.01,
	},
	["Kiwi"] = {
		["Description"] = "Nocturnal Nursery: Occasionally reduces the hatch time of the egg with the most hatch time left",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Kiwi"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://104651906442347",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 1000000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Nocturnal Nursery"
		},
		["YHeightScaler"] = 0.9,
	},
	["Mole"] = {
		["Description"] = "Treasure Hunter: Will occasionally dig down to find gear or sheckles",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Mole"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, 0),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://79089804794269",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 6,
		["SellPrice"] = 2000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Treasure Hunter"
		},
		["YHeightScaler"] = 0.1,
	},
	["Frog"] = {
		["Description"] = "Croak: Will occasionally advance a nearby plant\'s growth by 24 hours",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Frog"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://96930166899467",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 3000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Croak"
		},
		["YHeightScaler"] = 0.1,
	},
	["Echo Frog"] = {
		["Description"] = "Echo Croak: Will occasionally advance a nearby plant\'s growth by 24 hours",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Echo Frog"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://102271225890686",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 5000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Echo Croak"
		},
		["YHeightScaler"] = 0.1,
	},
	["Raccoon"] = {
		["Description"] = "Rascal: Occasionally steals (duplicates) fruit from other player\'s plot and hands it to you",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Raccoon"),
		["DefaultHunger"] = 45000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://136232391555861",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 20000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Rascal"
		},
		["YHeightScaler"] = 0.1,
	},
	["Night Owl"] = {
		["Description"] = "King of the Night: Grants bonus experience per second gain to all active pets.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Night Owl"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://101760640498094",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 15000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"King of the Night",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.5,
	},
	["Owl"] = {
		["Description"] = "Prince of the Night: Grants bonus experience per second gain to all active pets.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Owl"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://138016343005291",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 15000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Prince of the Night",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.5,
	},
	["Grey Mouse"] = {
		["Description"] = "Whisker Wisdom: Occasionally gains bonus experience & Scamper: Increase player movement speed",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Grey Mouse"),
		["DefaultHunger"] = 15000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://116310390398341",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 5500000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Whisker Wisdom",
			"Scamper"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Squirrel"] = {
		["Description"] = "Seed Stash: Grants a chance to not consume a use when using the reclaimer & Nutty Apology: Gains additional XP per second",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Squirrel"),
		["DefaultHunger"] = 15000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://96950434895806",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 5500000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Seed Stash",
			"Nutty Apology"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Brown Mouse"] = {
		["Description"] = "Whiskier Wisdom: Occasionally gains bonus experience & Cheese Hop: Increase player jump height",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Grey Mouse"),
		["Variant"] = "Brown Mouse",
		["DefaultHunger"] = 15000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://94641319183999",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 5500000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Whiskier Wisdom",
			"Cheese Hop"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Red Giant Ant"] = {
		["Description"] = "For the Red Colony: Small chance to duplicate harvested plant & Fruit Harvester: Increased chance to duplicate harvested fruit type plant",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Giant Ant"),
		["Variant"] = "Red Giant Ant",
		["DefaultHunger"] = 15000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, 3.141592653589793),
		["ModelScalePerLevel"] = 0.003,
		["Icon"] = "rbxassetid://89449712431551",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 5,
		["SellPrice"] = 10500000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"For the Red Colony",
			"Fruit Harvester"
		},
		["YHeightScaler"] = 0.4,
	},
	["Red Fox"] = {
		["Description"] = "Scoundrel: Every <Cooldown>m, goes to another player\'s plot and tries to steal a seed from a random plant. The rarer the plant, the harder it is to succeed!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Red Fox"),
		["DefaultHunger"] = 35000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://116662854190616",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 16,
		["SellPrice"] = 20500000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Scoundrel"
		},
		["YHeightScaler"] = 0.1,
	},
	["Chicken Zombie"] = {
		["Description"] = "Zombify: Occasionally has a chance to zombify a nearby random fruit & Eggcelerator: Decreases the time needed to hatch other eggs",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Chicken Zombie"),
		["DefaultHunger"] = 35000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://108581559611673",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 1000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Zombify",
			"Eggcelerator"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Blood Hedgehog"] = {
		["Description"] = "Sanguine Spike: Makes nearby prickly fruit have increased variant chance and grow bigger",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Blood Hedgehog"),
		["DefaultHunger"] = 30000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://76471191139414",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 7,
		["SellPrice"] = 33000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Sanguine Spike",
			"Prickly Blessing"
		},
		["YHeightScaler"] = 0.01,
	},
	["Blood Kiwi"] = {
		["Description"] = "Crimson Cradle: Occasionally reduces the egg hatch time and boosts egg hatch speed",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Blood Kiwi"),
		["DefaultHunger"] = 45000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://87343374343285",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 30000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Crimson Cradle",
			"Better Eggcelerator"
		},
		["YHeightScaler"] = 0.9,
	},
	["Blood Owl"] = {
		["Description"] = "Monarch of Midnight: Grants bonus experience per second gain to all active pets",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Blood Owl"),
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://81262783747840",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 70000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Monarch of Midnight",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.5,
	},
	["Moon Cat"] = {
		["Description"] = "Moon Nap: Moon cat naps in a random spot in your farm, and boosts nearby fruit size & Moon Harvest: Grants chance for Night type plants to replant when harvested ",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Cat"),
		["Variant"] = "Moon Cat",
		["DefaultHunger"] = 2400,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://72392850111255",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 25000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Moon Nap",
			"Moon Harvest"
		},
		["YHeightScaler"] = 0.4,
		["States"] = {}
	},
	["Bee"] = {
		["Description"] = "Pollinator: Occasionally pollinates fruit",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bee"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -3.141592653589793),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://114116135745614",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 400000,
		["Rarity"] = "Uncommon",
		["Passives"] = {
			"Pollinator"
		},
		["YHeightScaler"] = 0.2,
	},
	["Honey Bee"] = {
		["Description"] = "Beeter Pollinator: Occasionally pollinates fruit",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bee"),
		["Variant"] = "Honey Bee",
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -3.141592653589793),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://134999468799162",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 800000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Beeter Pollinator"
		},
		["YHeightScaler"] = 0.2,
	},
	["Petal Bee"] = {
		["Description"] = "Pollinator: Occasionally pollinates fruit & Flower Harvest: Harvested flowers have a chance to stay",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bee"),
		["Variant"] = "Petal Bee",
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -3.141592653589793),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://137924182648564",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 1000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Pollinator",
			"Flower Harvest"
		},
		["YHeightScaler"] = 0.03,
	},
	["Bear Bee"] = {
		["Description"] = "Wanna-Bee: Occasionally tries to pollinate fruit, but it just ends up being Honey-Glazed",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bear Bee"),
		["DefaultHunger"] = 45000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://97465846056354",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 4000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Wanna-Bee"
		},
		["YHeightScaler"] = 0.35,
	},
	["Queen Bee"] = {
		["Description"] = "Queen Pollinator: Occasionally pollinates fruit instantly & For the Queen: Occasionally refrehes the pet with the highest cooldown ability",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Queen Bee"),
		["DefaultHunger"] = 65000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -2.530727415391778),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://127281358672581",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 5,
		["SellPrice"] = 8000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Queen Pollinator",
			"For the Queen"
		},
		["YHeightScaler"] = 10,
	},
	["Wasp"] = {
		["Description"] = "Wasp Pollinator: Occasionally pollinates fruit & Stinger: Occasionally stings pet with highest cooldown advancing cooldown",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Wasp"),
		["DefaultHunger"] = 28000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://72767862942880",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 12,
		["SellPrice"] = 1000000,
		["Rarity"] = "Uncommon",
		["Passives"] = {
			"Wasp Pollinator",
			"Stinger"
		},
		["YHeightScaler"] = 0.2,
	},
	["Tarantula Hawk"] = {
		["Description"] = "Wasp Pollinator: Occasionally pollinates fruit & Tarantula Stinger: Occasionally stings pet with highest cooldown advancing cooldown",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Tarantula Hawk"),
		["DefaultHunger"] = 28000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://126203792467378",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 12,
		["SellPrice"] = 2000000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Pollinator",
			"Tarantula Stinger"
		},
		["YHeightScaler"] = 0.2,
	},
	["Moth"] = {
		["Description"] = "Silksong: Sings to a random pet and magically restore its hunger",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Moth"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://134180528391091",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 8,
		["SellPrice"] = 4000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Silksong"
		},
		["YHeightScaler"] = 0.2,
	},
	["Butterfly"] = {
		["Description"] = "Rainbow Flutter: Occasionally flies to a fruit with 4+ mutations, removes all mutations from it and converts it into rainbow. Ignores favorited fruit",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Butterfly"),
		["DefaultHunger"] = 26000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://119048229505161",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 8,
		["SellPrice"] = 8000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Rainbow Flutter"
		},
		["YHeightScaler"] = 0.2,
	},
	["Disco Bee"] = {
		["Description"] = "Disco Disco: Occasionally has a chance to turn a nearby fruit into Disco",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Disco Bee"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -3.141592653589793),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://139406192899443",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 12000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Disco Disco"
		},
		["YHeightScaler"] = 0.03,
	},
	["Cooked Owl"] = {
		["Description"] = "Let Him Cook: Occasionaly burns or cook a random nearby fruit & King of the Grill: Grants bonus experience per second gain to all active pets. Also very tasty!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Cooked Owl"),
		["ToolWeldOffset"] = true,
		["DefaultHunger"] = 50000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://78954652883059",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 3000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Let Him Cook",
			"King of the Grill",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.1,
	},
	["Pack Bee"] = {
		["Description"] = "Pack Bee: Increases backpack size by 25 and occasionally pollinates nearby fruit",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Pack Bee"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -3.141592653589793),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://105775306251306",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 2500000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Pollinator",
			"Pack Bee"
		},
		["YHeightScaler"] = 0.5,
	},
	["Starfish"] = {
		["Description"] = "You\'re a Star: Gains additional XP per second",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Starfish"),
		["DefaultHunger"] = 1500,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://120520383369074",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 0.25,
		["SellPrice"] = 50000,
		["Rarity"] = "Common",
		["Passives"] = {
			"You\'re a Star"
		},
		["YHeightScaler"] = 0.1,
		["States"] = {}
	},
	["Crab"] = {
		["Description"] = "Pinch Pocket: Occasionally goes to another player and pinches them and grants you a small amount of sheckles",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Crab"),
		["DefaultHunger"] = 3000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://73259620945174",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 4,
		["SellPrice"] = 60000,
		["Rarity"] = "Common",
		["Passives"] = {
			"Pinch Pocket"
		},
		["YHeightScaler"] = 0.8,
		["States"] = {}
	},
	["Seagull"] = {
		["Description"] = "Scavenger: Shoveling plants have a chance to drop the equivalent seed. Does not work on fruits",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Seagull"),
		["DefaultHunger"] = 3500,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://125267211322255",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 7,
		["SellPrice"] = 70000,
		["Rarity"] = "Common",
		["Passives"] = {
			"Movement Variation"
		},
		["YHeightScaler"] = 0.1,
		["States"] = {}
	},
	["Toucan"] = {
		["Description"] = "Tropical Lover: Makes all nearby Tropical type plants have increased variant chance and grow bigger",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Toucan"),
		["DefaultHunger"] = 9000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://118598422473758",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 7,
		["SellPrice"] = 880000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Tropical Lover",
			"Tropical Blessing",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.9,
	},
	["Flamingo"] = {
		["Description"] = "Flamboyance: Occasionally stands on one legs and all nearby plants will grow incredibly fast",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Flamingo"),
		["DefaultHunger"] = 14000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://122573642551827",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 880000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Flamboyance"
		},
		["YHeightScaler"] = 2.4,
	},
	["Sea Turtle"] = {
		["Description"] = "Shell Share: Occasionally shares its wisdom to a random active pet granting bonus experience & Water Splash: Occasionally has a chance to Wet a nearby fruit",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Sea Turtle"),
		["DefaultHunger"] = 22200,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.004,
		["Icon"] = "rbxassetid://136324651089948",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 1.5,
		["SellPrice"] = 880000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Shell Share",
			"Water Splash"
		},
		["YHeightScaler"] = 0.1,
		["States"] = {}
	},
	["Seal"] = {
		["Description"] = "Seal the Deal: When selling pets, has a small chance to get the pet back as its egg equivalent",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Seal"),
		["DefaultHunger"] = 17000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://70977930937021",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 6,
		["SellPrice"] = 880000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Seal the Deal"
		},
		["YHeightScaler"] = 0.1,
		["States"] = {}
	},
	["Orangutan"] = {
		["Description"] = "Helping Hands: When crafting, each material has a chance for it not to be consumed",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Orangutan"),
		["DefaultHunger"] = 55000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://91252752916705",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 6,
		["SellPrice"] = 880000,
		["Rarity"] = "Rare",
		["Passives"] = {
			"Helping Hands"
		},
		["YHeightScaler"] = 0.1,
		["States"] = {}
	},
	["Peacock"] = {
		["Description"] = "Utter Beauty: Occasionally fans its feathers and all nearby pets will advance ability cooldowns",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Peacock"),
		["DefaultHunger"] = 19000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://79434662175672",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Utter Beauty"
		},
		["YHeightScaler"] = 0.8,
		["States"] = {}
	},
	["Capybara"] = {
		["Description"] = "Chill Zone: Nearby pets\' hunger will not go down and they will gain additional xp per second",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Capybara"),
		["DefaultHunger"] = 30000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://109096250560950",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 5,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Chill Zone"
		},
		["YHeightScaler"] = 1.5,
	},
	["Scarlet Macaw"] = {
		["Description"] = "Verdant Bird: Occasionally has a chance to mutate nearby fruits Verdant",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Scarlet Macaw"),
		["DefaultHunger"] = 12000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://103592675269053",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 7,
		["SellPrice"] = 3300000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Verdant Bird",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.75,
	},
	["Ostrich"] = {
		["Description"] = "Eggsperience: Grants pets hatched from eggs an age bonus",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Ostrich"),
		["DefaultHunger"] = 20000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://85113894132517",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8.5,
		["SellPrice"] = 4400000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Eggsperience"
		},
		["YHeightScaler"] = 2.4,
	},
	["Mimic Octopus"] = {
		["Description"] = "Mimicry: Mimics and copies an ability from another pet and performs its ability",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Mimic Octopus"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://118831959038511",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 10000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Mimicry"
		},
		["YHeightScaler"] = 0.1,
		["States"] = {}
	},
	["Meerkat"] = {
		["Description"] = "Lookout: Occasionally goes to another pet and does a lookout for it. That pet advances cooldown. Has a chance chance to do it again after each lookout.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Meerkat"),
		["DefaultHunger"] = 22000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://111346621796974",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 1100000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Lookout"
		},
		["YHeightScaler"] = 1,
	},
	["Sand Snake"] = {
		["Description"] = "Coiled Commerce: Buying from the seed/gear shop has a small chance to duplicate the bought item!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Sand Snake"),
		["DefaultHunger"] = 28000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://110203289397199",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 6,
		["SellPrice"] = 1100000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Coiled Commerce"
		},
		["YHeightScaler"] = 0.1,
	},
	["Axolotl"] = {
		["Description"] = "Summer Regeneration: Summer type fruits have a chance to stay after collecting!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Axolotl"),
		["DefaultHunger"] = 22000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://115096754077953",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 5,
		["SellPrice"] = 3300000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Summer Regeneration"
		},
		["YHeightScaler"] = 0.5,
	},
	["Hyacinth Macaw"] = {
		["Description"] = "Wiltproof Bird: Occasionally has a chance to mutate nearby fruits Wiltproof",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Hyacinth Macaw"),
		["DefaultHunger"] = 12000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://118586950763516",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 7,
		["SellPrice"] = 4400000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Cloudtouched Bird",
			"Movement Variation"
		},
		["YHeightScaler"] = 0.75,
	},
	["Fennec Fox"] = {
		["Description"] = "Sly: Occasionally goes to another player\'s random fruit, has a chance to copy 1 mutation from it and applies it to a random fruit you own.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Fennec Fox"),
		["DefaultHunger"] = 35000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://106568248173155",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 16,
		["SellPrice"] = 7500000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Sly"
		},
		["YHeightScaler"] = 1.1,
	},
	["Hamster"] = {
		["Description"] = "Hamster Wheel: Occasionally runs in a hamster wheel and grants increased crafting speed for a duration",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Hamster"),
		["DefaultHunger"] = 15000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://95041454621458",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 3300000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Hamster Wheel"
		},
		["YHeightScaler"] = 0.5,
	},
	["Bald Eagle"] = {
		["Description"] = "Wings of Freedom: Every 7:04m, takes flight and spreads its wings. All eggs advanced their hatch time by 70.4s. There\'s a 7.04% chance for the effect to be multiplied",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bald Eagle"),
		["DefaultHunger"] = 15000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://100494018595907",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Wings of Freedom",
			"Movement Variation"
		},
		["YHeightScaler"] = 2,
	},
	["Raptor"] = {
		["Description"] = "Clever Claws: Small chance fruit gets Amber mutation after collecting! & Raptor Dance: Player has increased movement speed",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Raptor"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://133649762905181",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 12,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Clever Claws",
			"Raptor Dance"
		},
		["YHeightScaler"] = 0,
	},
	["Stegosaurus"] = {
		["Description"] = "Prehistoric Doubling: Small chance to duplicate harvested fruit & Prehistoric Harvester: Increased chance to duplicate harvested prehistoric type plant",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Stegosaurus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://115750504063562",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Prehistoric Doubling",
			"Prehistoric Harvester"
		},
		["YHeightScaler"] = 0,
	},
	["Triceratops"] = {
		["Description"] = "Tri-Horn: Rams into random plants and advances their growth",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Triceratops"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://133031079193526",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Tri-Horn"
		},
		["YHeightScaler"] = 0,
	},
	["Pterodactyl"] = {
		["Description"] = "Sky Reptile: Occasionally applies Windstruck mutation to multiple nearby fruits! & Air Time: Player has increased jump height",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Pterodactyl"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://132325249273328",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 10000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Sky Reptile",
			"Air Time",
			"Movement Variation"
		},
		["YHeightScaler"] = 1,
	},
	["Brontosaurus"] = {
		["Description"] = "Giant Incubator: Pets hatched from eggs have higher base weight",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Brontosaurus"),
		["DefaultHunger"] = 80000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://138431192706334",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 5,
		["SellPrice"] = 20000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Giant Incubator"
		},
		["YHeightScaler"] = 0,
	},
	["Radioactive Stegosaurus"] = {
		["Description"] = "Developer RemorsEcoDe\'s pet",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Radioactive Stegosaurus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://115750504063562",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Radioactive Lizard"
		},
		["YHeightScaler"] = 0,
	},
	["T-Rex"] = {
		["Description"] = "Apex Predator: Occasionally eats a random mutation from a fruit in your garden then roars and applies that mutation to other fruits in your garden.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("T-Rex"),
		["DefaultHunger"] = 60000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://72024850228702",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 40000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Apex Predator"
		},
		["YHeightScaler"] = 0.05,
	},
	["Parasaurolophus"] = {
		["Description"] = "Crowbar Head: Occasionally, goes to the cosmetic crate with the highest time and reduces time to open!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Parasaurolophus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://77060347493123",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Crowbar Head"
		},
		["YHeightScaler"] = 0.05,
	},
	["Iguanodon"] = {
		["Description"] = "Dino Herd: Grants bonus experience per second gain to all Dinosaur type active pets",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Iguanodon"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://132997806707299",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Dino Herd"
		},
		["YHeightScaler"] = 0.05,
	},
	["Pachycephalosaurus"] = {
		["Description"] = "Crafty Dome: Grants a small chance to duplicate the crafted item.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Pachycephalosaurus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://98967783170808",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 5000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Crafty Dome"
		},
		["YHeightScaler"] = 0.05,
	},
	["Dilophosaurus"] = {
		["Description"] = "Frilled Reptile: Occasionally opens its frills and spits out venom! The venom spreads to other random pets, advancing cooldown OR granting bonus xp",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Dilophosaurus"),
		["DefaultHunger"] = 30000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://88442192911950",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 10000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Frilled Reptile"
		},
		["YHeightScaler"] = 0.05,
	},
	["Ankylosaurus"] = {
		["Description"] = "Armored Defender: When a player steals a fruit from you, grants a chance you get the stolen fruit as well.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Ankylosaurus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://128962631009648",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 20000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Armored Defender"
		},
		["YHeightScaler"] = 0.05,
	},
	["Spinosaurus"] = {
		["Description"] = "Occasionally, devours a random mutation from random fruits in your garden each, roars and applies it to 1 other random fruit in your garden!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Spinosaurus"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://78132119445447",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 40000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Food Chain"
		},
		["YHeightScaler"] = 0.05,
	},
	["Rainbow Parasaurolophus"] = {
		["Description"] = "Crowbar Head: Occasionally, goes to the cosmetic crate with the highest time and reduces time to open!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rainbow Parasaurolophus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://116062422658499",
		["OddsIcon"] = "rbxassetid://125458280085952",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 10000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Rainbow Crowbar Head"
		},
		["YHeightScaler"] = 0.05,
	},
	["Rainbow Iguanodon"] = {
		["Description"] = "Dino Herd: Grants bonus experience per second gain to all Dinosaur type active pets",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rainbow Iguanodon"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://70960389100537",
		["OddsIcon"] = "rbxassetid://94572344496310",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 10000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Rainbow Dino Herd"
		},
		["YHeightScaler"] = 0.05,
	},
	["Rainbow Pachycephalosaurus"] = {
		["Description"] = "Crafty Dome: Grants a small chance to duplicate the crafted item.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rainbow Pachycephalosaurus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://71353461716145",
		["OddsIcon"] = "rbxassetid://104196332322283",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 10000000,
		["Rarity"] = "Legendary",
		["Passives"] = {
			"Rainbow Crafty Dome"
		},
		["YHeightScaler"] = 0.05,
	},
	["Rainbow Dilophosaurus"] = {
		["Description"] = "Frilled Reptile: Occasionally opens its frills and spits out venom! The venom spreads to other random pets, advancing cooldown OR granting bonus xp",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rainbow Dilophosaurus"),
		["DefaultHunger"] = 30000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://114260890723408",
		["OddsIcon"] = "rbxassetid://92472270160849",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 10,
		["SellPrice"] = 20000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Rainbow Frilled Reptile"
		},
		["YHeightScaler"] = 0.05,
	},
	["Rainbow Ankylosaurus"] = {
		["Description"] = "Armored Defender: When a player steals a fruit from you, grants a chance you get the stolen fruit as well.",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rainbow Ankylosaurus"),
		["DefaultHunger"] = 40000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://108330251202915",
		["OddsIcon"] = "rbxassetid://96359333884841",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 8,
		["SellPrice"] = 40000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Rainbow Armored Defender"
		},
		["YHeightScaler"] = 0.05,
	},
	["Rainbow Spinosaurus"] = {
		["Description"] = "Occasionally, devours a random mutation from random fruits in your garden each, roars and applies it to 1 other random fruit in your garden!",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Rainbow Spinosaurus"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 0, 0),
		["ToolWeldOffset"] = true,
		["TwoHanded"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://98134533729834",
		["OddsIcon"] = "rbxassetid://132599364727436",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Grounded",
		["MovementSpeed"] = 9,
		["SellPrice"] = 80000000,
		["Rarity"] = "Divine",
		["Passives"] = {
			"Rainbow Food Chain"
		},
		["YHeightScaler"] = 0.05,
	},
	["Firefly"] = {
		["Description"] = "Lightning Bug: Occasionally strikes a random nearby fruit, with a small chance of turning it Shocked",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Firefly"),
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 1.5707963267948966),
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://131310748087635",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 10,
		["SellPrice"] = 3300000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Lightning Bug"
		},
		["YHeightScaler"] = 0.5,
	},
	["Red Dragon"] = {
		["Description"] = "Scorched Soil: Occasionally sets a random nearby fruit ablaze, turning it into Burnt",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Red Dragon"),
		["DefaultHunger"] = 10000,
		["WeldOffset"] = CFrame.Angles(0, -1.5707963267948966, 0),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.004,
		["Icon"] = "rbxassetid://140223014467344",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 10,
		["SellPrice"] = 100000,
		["Rarity"] = "Common",
		["Passives"] = {
			"Scorched Soil"
		},
		["YHeightScaler"] = 0.2,
	},
	["Golden Bee"] = {
		["Description"] = "Pollinator: Occasionally pollinates fruit & Golden Harvest: Harvested fruit has a chance to turn to gold",
		["Actions"] = {},
		["Model"] = v5:FindFirstChild("Bee"),
		["Variant"] = "Golden Bee",
		["DefaultHunger"] = 25000,
		["WeldOffset"] = CFrame.Angles(0, 1.5707963267948966, -3.141592653589793),
		["ToolWeldOffset"] = true,
		["ModelScalePerLevel"] = 0.005,
		["Icon"] = "rbxassetid://125658111834879",
		["HungerFruitMultipliers"] = {},
		["MovementType"] = "Flight",
		["MovementSpeed"] = 9,
		["SellPrice"] = 1000000,
		["Rarity"] = "Mythical",
		["Passives"] = {
			"Pollinator",
			"Golden Harvest"
		},
		["YHeightScaler"] = 0.03,
	}
}
return v7
