local v1 = {
	["Cinder Shores"] = {
		["Location"] = "Cinder Shores",
		["ItemPool"] = {
			"Pebbles",
			"Battery",
			"Sock",
			"Cardboard Box",
			"Tin Can",
			"Clay",
			"Clump Of Sand",
			"Bottle",
			"Stick",
			"Slate",
			"Seaweed",
			"Fan Coral",
			"Tube Coral",
			"Plastic Bucket",
			"Coconut",
			"Worm",
			"Starfish",
			"Sand Dollar",
			"Limestone",
			"Barrel",
			"Fishing Hook",
			"Shark Tooth",
			"Sandals",
			"Glasses",
			"Fishing Rod",
			"Quartz",
			"Rubber Duck",
			"Umbrella",
			"Turtle",
			"Ship Helm",
			"Nautilis Fossil",
			"Marlin Fish",
			"Diamond Ring",
			"Bongos",
			"Palm Tree",
			"Shark Skull",
			"Fisch",
			"Duck Floatie",
			"Shark Plush",
			"Bold And Brash",
			"Giant Fish Cracker"
		},
		["Luck"] = 0,
		["Haste"] = 0,
		["Strength"] = 0,
		["Control"] = 0
	},
	["Cinder Shores [Rock]"] = {
		["Location"] = "Cinder Shores",
		["ItemPool"] = {
			"Pebbles",
			"Clay",
			"Sock",
			"Clump Of Sand",
			"Battery",
			"Soda Can",
			"Slate",
			"Coconut",
			"Pyrite",
			"Starfish",
			"Limestone",
			"Fishing Hook",
			"Quartz",
			"Rubber Duck",
			"Turtle",
			"Umbrella",
			"Ship Helm",
			"Nautilus Fossil",
			"Diamond Ring",
			"Shark Skull",
			"Duck Floatie",
			"Shark Plush",
			"Bold And Brash",
			"Giant Fish Cracker"
		},
		["Luck"] = 0,
		["Haste"] = 0,
		["Strength"] = 0,
		["Control"] = 0
	}
}
local v2 = {
	["Location"] = "Fernhill Forest",
	["ItemPool"] = {
		"Pebbles",
		"Cardboard Box",
		"Tin Can",
		"Stick",
		"Clay",
		"Lost Shrubs",
		"Cinder Block",
		"Cog",
		"Boot",
		"Soda Can",
		"Rock Chunk",
		"Compass",
		"Pinecone",
		"Acorn",
		"Tire",
		"Old Coin",
		"Log",
		"Metal Pipe",
		"Wood Plank",
		"Worm",
		"Hampster",
		"Ring",
		"Envelope",
		"Broken Monitor",
		"Barrel",
		"Lunch Box",
		"Carnelian",
		"Morpho Butterfly",
		"Bunny",
		"Woodpecker",
		"Wanwood Crown",
		"Salamander",
		"Feather",
		"Baseball Bat",
		"Grabby Arm",
		"Couch",
		"Pendant",
		"Magnifying Glass",
		"Frog",
		"Snake",
		"Tulips",
		"Kazoo",
		"Sniffles Egg",
		"Tree",
		"Tiger Frog",
		"Teddy Bear",
		"Future Paths",
		"Diamond Ring",
		"Pet Rock",
		"Mole",
		"TeeVee",
		"Wagon",
		"Banishing Hammer",
		"OMB",
		"Gnome",
		"Teddy Bear",
		"Old Car",
		"Pot of Gold",
		"Awfully Tall Pillar Of Concrete"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Magnet Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1,
			{ 1, 2 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Fernhill Forest"] = v2
local v3 = {
	["Location"] = "Fernhill Forest",
	["ItemPool"] = {
		"Pebbles",
		"Battery",
		"Stick",
		"Cardboard Box",
		"Tin Can",
		"Clay",
		"Lost Shrubs",
		"Cinder Block",
		"Cog",
		"Boot",
		"Soda Can",
		"Rock Chunk",
		"Compass",
		"Pinecone",
		"Acorn",
		"Tire",
		"Old Coin",
		"Log",
		"Bread",
		"Metal Pipe",
		"Wood Plank",
		"Hampster",
		"Ring",
		"Envelope",
		"Tulips",
		"Broken Monitor",
		"Barrel",
		"Lunch Box",
		"Carnelian",
		"Morpho Butterfly",
		"Cake",
		"Traffic Cone",
		"Bunny",
		"Sapphire",
		"Washing Machine",
		"Worm",
		"Wanwood Crown",
		"Salamander",
		"Feather",
		"Baseball Bat",
		"Grabby Arm",
		"Couch",
		"Magnifying Glass",
		"Pendant",
		"Frog",
		"Snake",
		"Kazoo",
		"Sniffles Egg",
		"Tree",
		"Teddy Bear",
		"Future Paths",
		"Bowling Trophy",
		"Diamond Ring",
		"Pet Rock",
		"Mole",
		"TeeVee",
		"Wagon",
		"Banishing Hammer",
		"Gnome",
		"Old Car",
		"Pot of Gold"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Magnet Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1,
			{ 1, 2 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Fernhill Forest [Fox Town]"] = v3
local v4 = {
	["Location"] = "Fernhill Forest",
	["ItemPool"] = {
		"Pebbles",
		"Tin Can",
		"Clay",
		"Cinder Block",
		"Boot",
		"Slate",
		"Rock Chunk",
		"Compass",
		"Tire",
		"Old Coin",
		"Coal",
		"Metal Pipe",
		"Pyrite",
		"Ring",
		"Worm",
		"Broken Monitor",
		"Envelope",
		"Lunch Box",
		"Carnelian",
		"Calcite",
		"Limestone",
		"Sapphire",
		"Grabby Arm",
		"Quartz",
		"Magnifying Glass",
		"Tungsten",
		"Pendant",
		"Flute",
		"Kazoo",
		"Sniffles Egg",
		"Gold Nugget",
		"Tiger Frog",
		"Diamond Ring",
		"Pet Rock",
		"Cave Painting [Mighty]",
		"Cave Painting [Bull Hoard]",
		"TeeVee",
		"The Grandfather",
		"Banishing Hammer",
		"Gnome",
		"Old Car",
		"Pot of Gold"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Magnet Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1,
			{ 1, 2 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Fernhill Forest [Stone]"] = v4
local v5 = {
	["Location"] = "Rooftop Woodlands",
	["ItemPool"] = {
		"Pebbles",
		"Clay",
		"Stick",
		"Wild Berries",
		"Wilted Flower",
		"Slate",
		"Redcap Mushroom",
		"Snail",
		"Barrel",
		"Browncap Mushroom",
		"Mouse",
		"Ring",
		"Gravestone",
		"Woodpecker",
		"Roses",
		"Crow",
		"Coffin",
		"Wisp",
		"Raccoon",
		"Dark Oak Tree",
		"Ghost",
		"Woodlands Staff",
		"Brown Bear",
		"Pot of Gold",
		"Finns Sword"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.5,
			{ 1, 3 }
		},
		["Magnet Crate"] = {
			0.2,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1111111111111111,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Rooftop Woodlands"] = v5
local v6 = {
	["Location"] = "Rooftop Woodlands",
	["ItemPool"] = {
		"Pebbles",
		"Clay",
		"Stick",
		"Wild Berries",
		"Wilted Flower",
		"Slate",
		"Redcap Mushroom",
		"Snail",
		"Barrel",
		"Browncap Mushroom",
		"Mouse",
		"Ring",
		"Gravestone",
		"Woodpecker",
		"Roses",
		"Crow",
		"Coffin",
		"Wisp",
		"Skeleton Hand",
		"Raccoon",
		"Ghost",
		"Woodlands Staff",
		"Brown Bear",
		"Pot of Gold",
		"Finns Sword"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.5,
			{ 1, 3 }
		},
		["Magnet Crate"] = {
			0.2,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1111111111111111,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Rooftop Woodlands [Grave Yard]"] = v6
local v7 = {
	["Location"] = "Rooftop Woodlands",
	["ItemPool"] = {
		"Pebbles",
		"Clay",
		"Stick",
		"Slate",
		"Snail",
		"Redcap Mushroom",
		"Pyrite",
		"Starfish",
		"Limestone",
		"Ring",
		"Gravestone",
		"Browncap Mushroom",
		"Crow",
		"Coffin",
		"Diamond Ring",
		"Wisp",
		"Dark Oak Tree",
		"Raccoon",
		"Ghost",
		"Brown Bear",
		"Pot of Gold",
		"Finns Sword",
		"Awfully Tall Pillar Of Concrete"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.5,
			{ 1, 3 }
		},
		["Magnet Crate"] = {
			0.2,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1111111111111111,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Rooftop Woodlands [Rock]"] = v7
local v8 = {
	["Location"] = "Verdant Vale",
	["ItemPool"] = {
		"Clay",
		"Boot",
		"Stick",
		"Soda Can",
		"Apple",
		"Glasses",
		"Egg",
		"Carrot",
		"Onion",
		"Millipede",
		"Cow Bell",
		"Ring",
		"Bees Nest",
		"Chicken",
		"Fourleaf Clover",
		"Eggplant",
		"Watering Can",
		"Sunflower",
		"Tractor Engine",
		"Tractor Steering Wheel",
		"Giant Seed",
		"Bee",
		"Scarecrow",
		"Pie",
		"Pig",
		"Enigma",
		"Scythe",
		"Goat",
		"Weaponized Stick",
		"Pickle",
		"Cow",
		"Turnip Head",
		"Rift In A Jar"
	},
	["ToolPool"] = {
		["Magnet Crate"] = {
			0.5,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.05,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Verdant Vale"] = v8
local v9 = {
	["Location"] = "Verdant Vale",
	["ItemPool"] = {
		"Clay",
		"Soda Can",
		"Rock Chunk",
		"Glasses",
		"Millipede",
		"Aquamarine",
		"Chicken",
		"Barrel",
		"Watering Can",
		"Tractor Tire",
		"Tractor Steering Wheel",
		"Scarecrow",
		"Pie",
		"Enigma",
		"Goat",
		"Pickle",
		"Cow",
		"Turnip Head",
		"Rift In A Jar"
	},
	["ToolPool"] = {
		["Magnet Crate"] = {
			0.5,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.05,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Verdant Vale [Stone]"] = v9
local v10 = {
	["Location"] = "Cinder Cavern",
	["ItemPool"] = {
		"Clay",
		"Chalk",
		"Gravel",
		"Slate",
		"Coal",
		"Raw Copper",
		"Metal Pipe",
		"Pickaxe",
		"Glowstick",
		"Aquamarine",
		"Sulfur",
		"Barrel",
		"Raw Iron",
		"Spider",
		"Gas Can",
		"Peridot",
		"Sapphire",
		"Tungsten",
		"Amethyst",
		"Topaz",
		"Cave Bat",
		"Ruby",
		"Jackhammer",
		"Gold Nugget",
		"Emerald",
		"Diglite",
		"Gold Cart",
		"Tanzanite",
		"Rock Statue",
		"Celestial Crystal",
		"Diamond",
		"Jin, The God of Gold",
		"Golem",
		"Unformed Object",
		"Sentient Boombox"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.5,
			{ 1, 3 }
		},
		["Magnet Crate"] = {
			0.25,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.06666666666666667,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Cavern"] = v10
local v11 = {
	["Location"] = "Cinder Cavern",
	["ItemPool"] = {
		"Clay",
		"Chalk",
		"Gravel",
		"Slate",
		"Coal",
		"Raw Copper",
		"Pickaxe",
		"Glowstick",
		"Aquamarine",
		"Sulfur",
		"Barrel",
		"Raw Iron",
		"Spider",
		"Gas Can",
		"Sapphire",
		"Tungsten",
		"Amethyst",
		"Topaz",
		"Cave Bat",
		"Ruby",
		"Gold Nugget",
		"Emerald",
		"Diglite",
		"Gold Cart",
		"Tanzanite",
		"Rock Statue",
		"Diamond",
		"Hypno Blueshroom",
		"Unformed Object",
		"Sentient Boombox"
	},
	["ToolPool"] = {
		["Enchantment Tome"] = {
			0.125,
			{ 1, 2 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Cavern [Azure]"] = v11
v1["Cinder Cavern [Spiders Keep]"] = {
	["Location"] = "Cinder Cavern",
	["ItemPool"] = {
		"Clay",
		"Chalk",
		"Gravel",
		"Slate",
		"Coal",
		"Raw Copper",
		"Metal Pipe",
		"Pickaxe",
		"Glowstick",
		"Aquamarine",
		"Sulfur",
		"Spider Eye",
		"Barrel",
		"Raw Iron",
		"Spider",
		"Gas Can",
		"Sapphire",
		"Tungsten",
		"Amethyst",
		"Topaz",
		"Cave Bat",
		"Ruby",
		"Gold Nugget",
		"Emerald",
		"Diglite",
		"Gold Cart",
		"Rock Statue",
		"Diamond",
		"Jin, The God of Gold",
		"Unformed Object",
		"Sentient Boombox"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Approach"] = {
	["Location"] = "Cinder Approach",
	["ItemPool"] = {
		"Pebbles",
		"Cardboard Box",
		"Tin Can",
		"Stick",
		"Clay",
		"Lost Shrubs",
		"Cinder Block",
		"Cog",
		"Boot",
		"Rock Chunk",
		"Compass",
		"Pinecone",
		"Acorn",
		"Tire",
		"Old Coin",
		"Log",
		"Metal Pipe",
		"Worm",
		"Hampster",
		"Ring",
		"Envelope",
		"Broken Monitor",
		"Lunch Box",
		"Barrel",
		"Carnelian",
		"Morpho Butterfly",
		"Bunny",
		"Wanwood Crown",
		"Salamander",
		"Feather",
		"Baseball Bat",
		"Grabby Arm",
		"Couch",
		"Pendant",
		"Magnifying Glass",
		"Frog",
		"Snake",
		"Kazoo",
		"Sniffles Egg",
		"Tree",
		"Teddy Bear",
		"Future Paths",
		"Diamond Ring",
		"Pet Rock",
		"Mole",
		"TeeVee",
		"Wagon",
		"Banishing Hammer",
		"OMB",
		"Gnome",
		"Teddy Bear",
		"Old Car",
		"Pot of Gold",
		"Awfully Tall Pillar Of Concrete"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Approach [Stone]"] = {
	["Location"] = "Cinder Approach",
	["ItemPool"] = {
		"Pebbles",
		"Tin Can",
		"Clay",
		"Cinder Block",
		"Boot",
		"Slate",
		"Rock Chunk",
		"Compass",
		"Tire",
		"Old Coin",
		"Coal",
		"Metal Pipe",
		"Worm",
		"Pyrite",
		"Ring",
		"Broken Monitor",
		"Envelope",
		"Lunch Box",
		"Carnelian",
		"Barrel",
		"Calcite",
		"Limestone",
		"Sapphire",
		"Grabby Arm",
		"Quartz",
		"Magnifying Glass",
		"Tungsten",
		"Pendant",
		"Kazoo",
		"Sniffles Egg",
		"Gold Nugget",
		"Diamond Ring",
		"Pet Rock",
		"Cave Painting [Mighty]",
		"Cave Painting [Bull Hoard]",
		"TeeVee",
		"The Grandfather",
		"Banishing Hammer",
		"Gnome",
		"Old Car",
		"Pot of Gold",
		"Unformed Object"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Mountain"] = {
	["Location"] = "Mount Cinder",
	["ItemPool"] = {
		"Pebbles",
		"Clump Of Snow",
		"Stick",
		"Icicle",
		"Toothpaste",
		"Snow Berry",
		"Old Harp",
		"Beanie",
		"Block Of Ice",
		"Popsicle",
		"Yogurt",
		"Snowball",
		"Ice Pick",
		"Barrel",
		"Sled",
		"Ice Cream",
		"Snowboard",
		"Penguin",
		"Snowman",
		"Frost Lily",
		"Fridge",
		"Giant Bell",
		"Polar Bear",
		"Pine Tree",
		"Frozen Person",
		"Jukebox",
		"Woolly Mammoth",
		"Ice Sculpture",
		"Light Plane",
		"Ice Staff",
		"The Thinker"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Mountain [Stone]"] = {
	["Location"] = "Mount Cinder",
	["ItemPool"] = {
		"Pebbles",
		"Clay",
		"Icicle",
		"Toothpaste",
		"Slate",
		"Beanie",
		"Block Of Ice",
		"Popsicle",
		"Ice Pick",
		"Old Harp",
		"Barrel",
		"Ice Cream",
		"Snowboard",
		"Fridge",
		"Jukebox",
		"Emerald",
		"Pine Tree",
		"Frozen Person",
		"Cave Painting [Snowball Fight]",
		"Ice Sculpture",
		"Giant Bell",
		"Light Plane",
		"Ice Staff",
		"The Thinker"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Cinder Mountain [Glacial Grotto]"] = {
	["Location"] = "Mount Cinder",
	["ItemPool"] = {
		"Clump Of Snow",
		"Toothpaste",
		"Beanie",
		"Block Of Ice",
		"Popsicle",
		"Yogurt",
		"Ice Cream",
		"Thermometer",
		"Snowcone",
		"Snowball",
		"Snowboard",
		"Fridge",
		"Jukebox",
		"Frost Lily",
		"Snowman",
		"Emerald",
		"Frozen Person",
		"Cave Painting [Snowball Fight]",
		"Snowflake",
		"Ice Sculpture",
		"Giant Bell",
		"Frost Bug",
		"Light Plane",
		"Ice Staff",
		"Ice Tree",
		"The Thinker"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Copper Mesa"] = {
	["Location"] = "Copper Mesa",
	["ItemPool"] = {
		"Pebbles",
		"Stick",
		"Clay Shard",
		"Tin Can",
		"Water Bottle",
		"Soda Can",
		"Raw Copper",
		"Cactus Chunk",
		"Copper Coin",
		"Sandstone",
		"Granite",
		"Potato",
		"Gold Pan",
		"Millipede",
		"Cactus",
		"Hour Glass",
		"Sheriff Badge",
		"Tumbleweed",
		"Goblet",
		"Smooth Vase",
		"Lavender Flowers",
		"Washboard",
		"Dung Beetle",
		"Gold Nugget",
		"Spear",
		"Scorpion",
		"Citrine",
		"Lasso",
		"Dinosaur Spine",
		"Jukebox",
		"Megaphone",
		"Camel",
		"Pinata",
		"Velociraptor Skull",
		"Wagon",
		"Vulture",
		"Desert Ferret",
		"Jukebox",
		"Revolver",
		"Talking Bass",
		"Bison",
		"Horse",
		"Laser Saber",
		"Ocarina",
		"Burger Statue",
		"Long Horse"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Copper Mesa [Rock]"] = {
	["Location"] = "Copper Mesa",
	["ItemPool"] = {
		"Pebbles",
		"Stick",
		"Clay Shard",
		"Tin Can",
		"Water Bottle",
		"Soda Can",
		"Raw Copper",
		"Cactus Chunk",
		"Copper Coin",
		"Sandstone",
		"Granite",
		"Potato",
		"Gold Pan",
		"Cactus",
		"Hour Glass",
		"Sheriff Badge",
		"Tumbleweed",
		"Smooth Vase",
		"Lavender Flowers",
		"Washboard",
		"Dung Beetle",
		"Gold Nugget",
		"Spear",
		"Citrine",
		"Lasso",
		"Dinosaur Spine",
		"Camel",
		"Pinata",
		"Velociraptor Skull",
		"Vulture",
		"Desert Ferret",
		"Jukebox",
		"Revolver",
		"Meteor",
		"Wagon",
		"Talking Bass",
		"Bison",
		"Horse",
		"Laser Saber",
		"Ocarina",
		"Burger Statue",
		"Long Horse"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Copper Mesa [Canyon]"] = {
	["Location"] = "Copper Mesa",
	["ItemPool"] = {
		"Pebbles",
		"Stick",
		"Clay Shard",
		"Tin Can",
		"Water Bottle",
		"Soda Can",
		"Raw Copper",
		"Cactus Chunk",
		"Copper Coin",
		"Sandstone",
		"Granite",
		"Potato",
		"Gold Pan",
		"Cactus",
		"Hour Glass",
		"Sheriff Badge",
		"Tumbleweed",
		"Smooth Vase",
		"Lavender Flowers",
		"Washboard",
		"Dung Beetle",
		"Gold Nugget",
		"Spear",
		"Scorpion",
		"Dead Tree",
		"Citrine",
		"Lasso",
		"Dinosaur Spine",
		"Megaphone",
		"Camel",
		"Pinata",
		"Velociraptor Skull",
		"Wagon",
		"Vulture",
		"Desert Ferret",
		"Jukebox",
		"Revolver",
		"Meteor",
		"Talking Bass",
		"Bison",
		"Horse",
		"Laser Saber",
		"Ocarina",
		"Burger Statue",
		"Long Horse"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Alona Jungle"] = {
	["Location"] = "Alona Jungle",
	["ItemPool"] = {
		"Pebbles",
		"Stick",
		"Dragon Fruit",
		"Papaya",
		"Jungle Blowpipe",
		"Bamboo",
		"Venus Flytrap",
		"Kunai",
		"Machete",
		"Ceremonial Drum",
		"Monkey",
		"Ritual Mask",
		"Macaw",
		"Ruby",
		"Telescope",
		"Capybara",
		"Life Fruit",
		"Golden Idol",
		"Toucan",
		"Panda",
		"Giraffe",
		"Butter Box"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1["Mount Charcoal"] = {
	["Location"] = "Mount Charcoal",
	["ItemPool"] = {
		"Pebbles",
		"Molten Rock",
		"Obsidian",
		"Chili Pepper",
		"Chain",
		"Volcano Spike",
		"Sulfur",
		"Hot Sauce",
		"Anvil",
		"Fire Flower",
		"Lava Bucket",
		"Magma Crystal",
		"Lava Worm",
		"Phoenix Feather",
		"Cave Painting [Uproar]",
		"Rigby"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
local v12 = {
	["Location"] = "Fernhill Forest",
	["ItemPool"] = {
		"Pebbles",
		"Cardboard Box",
		"Tin Can",
		"Stick",
		"Clay",
		"Lost Shrubs",
		"Cinder Block",
		"Cog",
		"Boot",
		"Soda Can",
		"Rock Chunk",
		"Compass",
		"Pinecone",
		"Acorn",
		"Tire",
		"Old Coin",
		"Log",
		"Metal Pipe",
		"Worm",
		"Hampster",
		"Ring",
		"Envelope",
		"Broken Monitor",
		"Barrel",
		"Lunch Box",
		"Carnelian",
		"Morpho Butterfly",
		"Bunny",
		"Wanwood Crown",
		"Salamander",
		"Feather",
		"Baseball Bat",
		"Grabby Arm",
		"Couch",
		"Pendant",
		"Magnifying Glass",
		"Frog",
		"Snake",
		"Tulips",
		"Kazoo",
		"Sniffles Egg",
		"Tree",
		"Teddy Bear",
		"Future Paths",
		"Diamond Ring",
		"Pet Rock",
		"Mole",
		"TeeVee",
		"Wagon",
		"Banishing Hammer",
		"OMB",
		"Gnome",
		"Teddy Bear",
		"The Virus",
		"Awfully Tall Pillar Of Concrete"
	},
	["ToolPool"] = {
		["Basic Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Magnet Crate"] = {
			0.3333333333333333,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.1,
			{ 1, 2 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1.Interlude = v12
v1.Jail = {
	["Location"] = "Fernhill Forest",
	["ItemPool"] = {
		"Pebbles",
		"Tin Can",
		"Cinder Block",
		"Boot",
		"Soda Can",
		"Toothpaste",
		"Lunch Box"
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
local v13 = {
	["Location"] = "Fernhill Forest",
	["ItemPool"] = {},
	["ToolPool"] = {
		["Basic Crate"] = {
			2,
			{ 1, 2 }
		},
		["Magnet Crate"] = {
			3,
			{ 1, 2 }
		},
		["Enchantment Tome"] = {
			0.3,
			{ 1, 2 }
		},
		["Horizon Horn"] = {
			0.15,
			{ 1, 1 }
		},
		["Windcaller Horn"] = {
			0.04,
			{ 1, 1 }
		},
		["Stormcaller Horn"] = {
			0.04,
			{ 1, 1 }
		},
		["Tempest Horn"] = {
			0.04,
			{ 1, 1 }
		}
	},
	["Luck"] = 0,
	["Haste"] = 0,
	["Strength"] = 0,
	["Control"] = 0
}
v1.MagnetShovelToolPool = v13
return v1
